Concatenating all excel sheets in a single CSV file (for even sem 23-24):

In [1]:
import pandas as pd
import os
data_dir = '../data'

Courses:

In [2]:
courses = pd.read_csv(os.path.join(data_dir, 'courses.csv'))

In [13]:
courses.sort_values(by=['category', 'course name'], ascending=[False, True], inplace=True)
courses

                                course name      category
28                            Art of living     Spiritual
3               Introduction to Bhagvadgita     Spiritual
14                                Pranvidya     Spiritual
29                                Yog Vidya     Spiritual
16  Mentoring of School Children (Abhudaya)        Social
32                    Mentorship to Juniors        Social
15                                      NSS        Social
40            Principle Centered Leadership        Social
30                   Teaching Assistantship        Social
8                         Terrace Gardening        Social
27      Volunteering at Dr. Amte's Anandvan        Social
7                             Wall Painting        Social
6                          Working with NGO        Social
25                                  Astitva      Physical
37                                   Kathak      Physical
36                         Physical Fitness      Physical
12                                  Running      Physical
11                   Self Defense for Women      Physical
10                                 Skipping      Physical
18                                   Sports      Physical
9                        Staircase Climbing      Physical
31                                 Swimming      Physical
26                                Taekwondo      Physical
1                                  Trekking      Physical
24                            Basic Cooking  Intellectual
23                     Basic of Fire Safety  Intellectual
33               Basics of Keyboard playing  Intellectual
38              Basics of Music Composition  Intellectual
4                           Design Thinking  Intellectual
22                        Film Appreciation  Intellectual
21              Fundamentals of Photography  Intellectual
20                                 Idea Lab  Intellectual
19                  Indian Knowledge System  Intellectual
5                 Innovation and Creativity  Intellectual
13                              Read a book  Intellectual
39        Short Film Making/ Cinematography  Intellectual
35                        Social Psychology  Intellectual
2                             Study of Life  Intellectual
34              Technology Entrepreneurship  Intellectual
17       Integrated Personality Development     Emotional
41         Jeevan Vidya (Work Life Balance)     Emotional
0                     Universal Human Value     Emotional

In [14]:
courses.reset_index(inplace=True, drop=True)
courses

                                course name      category
0                             Art of living     Spiritual
1               Introduction to Bhagvadgita     Spiritual
2                                 Pranvidya     Spiritual
3                                 Yog Vidya     Spiritual
4   Mentoring of School Children (Abhudaya)        Social
5                     Mentorship to Juniors        Social
6                                       NSS        Social
7             Principle Centered Leadership        Social
8                    Teaching Assistantship        Social
9                         Terrace Gardening        Social
10      Volunteering at Dr. Amte's Anandvan        Social
11                            Wall Painting        Social
12                         Working with NGO        Social
13                                  Astitva      Physical
14                                   Kathak      Physical
15                         Physical Fitness      Physical
16                                  Running      Physical
17                   Self Defense for Women      Physical
18                                 Skipping      Physical
19                                   Sports      Physical
20                       Staircase Climbing      Physical
21                                 Swimming      Physical
22                                Taekwondo      Physical
23                                 Trekking      Physical
24                            Basic Cooking  Intellectual
25                     Basic of Fire Safety  Intellectual
26               Basics of Keyboard playing  Intellectual
27              Basics of Music Composition  Intellectual
28                          Design Thinking  Intellectual
29                        Film Appreciation  Intellectual
30              Fundamentals of Photography  Intellectual
31                                 Idea Lab  Intellectual
32                  Indian Knowledge System  Intellectual
33                Innovation and Creativity  Intellectual
34                              Read a book  Intellectual
35        Short Film Making/ Cinematography  Intellectual
36                        Social Psychology  Intellectual
37                            Study of Life  Intellectual
38              Technology Entrepreneurship  Intellectual
39       Integrated Personality Development     Emotional
40         Jeevan Vidya (Work Life Balance)     Emotional
41                    Universal Human Value     Emotional

In [15]:
courses['course_id'] = courses.index
courses.rename(columns={'course name': 'course_name'}, inplace=True)
courses

                                course_name      category  course_id
0                             Art of living     Spiritual          0
1               Introduction to Bhagvadgita     Spiritual          1
2                                 Pranvidya     Spiritual          2
3                                 Yog Vidya     Spiritual          3
4   Mentoring of School Children (Abhudaya)        Social          4
5                     Mentorship to Juniors        Social          5
6                                       NSS        Social          6
7             Principle Centered Leadership        Social          7
8                    Teaching Assistantship        Social          8
9                         Terrace Gardening        Social          9
10      Volunteering at Dr. Amte's Anandvan        Social         10
11                            Wall Painting        Social         11
12                         Working with NGO        Social         12
13                                  Astitva      Physical         13
14                                   Kathak      Physical         14
15                         Physical Fitness      Physical         15
16                                  Running      Physical         16
17                   Self Defense for Women      Physical         17
18                                 Skipping      Physical         18
19                                   Sports      Physical         19
20                       Staircase Climbing      Physical         20
21                                 Swimming      Physical         21
22                                Taekwondo      Physical         22
23                                 Trekking      Physical         23
24                            Basic Cooking  Intellectual         24
25                     Basic of Fire Safety  Intellectual         25
26               Basics of Keyboard playing  Intellectual         26
27              Basics of Music Composition  Intellectual         27
28                          Design Thinking  Intellectual         28
29                        Film Appreciation  Intellectual         29
30              Fundamentals of Photography  Intellectual         30
31                                 Idea Lab  Intellectual         31
32                  Indian Knowledge System  Intellectual         32
33                Innovation and Creativity  Intellectual         33
34                              Read a book  Intellectual         34
35        Short Film Making/ Cinematography  Intellectual         35
36                        Social Psychology  Intellectual         36
37                            Study of Life  Intellectual         37
38              Technology Entrepreneurship  Intellectual         38
39       Integrated Personality Development     Emotional         39
40         Jeevan Vidya (Work Life Balance)     Emotional         40
41                    Universal Human Value     Emotional         41

In [16]:
courses = courses[['course_id', 'course_name', 'category']]
courses

    course_id                              course_name      category
0           0                            Art of living     Spiritual
1           1              Introduction to Bhagvadgita     Spiritual
2           2                                Pranvidya     Spiritual
3           3                                Yog Vidya     Spiritual
4           4  Mentoring of School Children (Abhudaya)        Social
5           5                    Mentorship to Juniors        Social
6           6                                      NSS        Social
7           7            Principle Centered Leadership        Social
8           8                   Teaching Assistantship        Social
9           9                        Terrace Gardening        Social
10         10      Volunteering at Dr. Amte's Anandvan        Social
11         11                            Wall Painting        Social
12         12                         Working with NGO        Social
13         13                                  Astitva      Physical
14         14                                   Kathak      Physical
15         15                         Physical Fitness      Physical
16         16                                  Running      Physical
17         17                   Self Defense for Women      Physical
18         18                                 Skipping      Physical
19         19                                   Sports      Physical
20         20                       Staircase Climbing      Physical
21         21                                 Swimming      Physical
22         22                                Taekwondo      Physical
23         23                                 Trekking      Physical
24         24                            Basic Cooking  Intellectual
25         25                     Basic of Fire Safety  Intellectual
26         26               Basics of Keyboard playing  Intellectual
27         27              Basics of Music Composition  Intellectual
28         28                          Design Thinking  Intellectual
29         29                        Film Appreciation  Intellectual
30         30              Fundamentals of Photography  Intellectual
31         31                                 Idea Lab  Intellectual
32         32                  Indian Knowledge System  Intellectual
33         33                Innovation and Creativity  Intellectual
34         34                              Read a book  Intellectual
35         35        Short Film Making/ Cinematography  Intellectual
36         36                        Social Psychology  Intellectual
37         37                            Study of Life  Intellectual
38         38              Technology Entrepreneurship  Intellectual
39         39       Integrated Personality Development     Emotional
40         40         Jeevan Vidya (Work Life Balance)     Emotional
41         41                    Universal Human Value     Emotional

In [18]:
courses['course_id'] += 1
courses.to_csv(os.path.join(data_dir, 'courses.csv'), index=False)

In [2]:
courses = pd.read_csv(os.path.join(data_dir, 'courses.csv'))
courses

    course_id                              course_name      category
0           1                            Art of living     Spiritual
1           2              Introduction to Bhagvadgita     Spiritual
2           3                                Pranvidya     Spiritual
3           4                                Yog Vidya     Spiritual
4           5  Mentoring of School Children (Abhudaya)        Social
5           6                    Mentorship to Juniors        Social
6           7                                      NSS        Social
7           8            Principle Centered Leadership        Social
8           9                   Teaching Assistantship        Social
9          10                        Terrace Gardening        Social
10         11      Volunteering at Dr. Amte's Anandvan        Social
11         12                            Wall Painting        Social
12         13                         Working with NGO        Social
13         14                                  Astitva      Physical
14         15                                   Kathak      Physical
15         16                         Physical Fitness      Physical
16         17                                  Running      Physical
17         18                   Self Defense for Women      Physical
18         19                                 Skipping      Physical
19         20                                   Sports      Physical
20         21                       Staircase Climbing      Physical
21         22                                 Swimming      Physical
22         23                                Taekwondo      Physical
23         24                                 Trekking      Physical
24         25                            Basic Cooking  Intellectual
25         26                     Basic of Fire Safety  Intellectual
26         27               Basics of Keyboard playing  Intellectual
27         28              Basics of Music Composition  Intellectual
28         29                          Design Thinking  Intellectual
29         30                        Film Appreciation  Intellectual
30         31              Fundamentals of Photography  Intellectual
31         32                                 Idea Lab  Intellectual
32         33                  Indian Knowledge System  Intellectual
33         34                Innovation and Creativity  Intellectual
34         35                              Read a book  Intellectual
35         36        Short Film Making/ Cinematography  Intellectual
36         37                        Social Psychology  Intellectual
37         38                            Study of Life  Intellectual
38         39              Technology Entrepreneurship  Intellectual
39         40       Integrated Personality Development     Emotional
40         41         Jeevan Vidya (Work Life Balance)     Emotional
41         42                    Universal Human Value     Emotional

Starting with even sem 23-24:

In [20]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.2-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Using cached openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2
Note: you may need to restart the kernel to use updated packages.

even sem 2023-24.xlsx file contains 33 sheets, first one is NPTEL

In [43]:
df = pd.read_excel(os.path.join(data_dir, 'even sem 2023-24.xlsx'), sheet_name=1)

In [44]:
df

,Email Address,Name (as in the college records),UID No.,Class (to be entered in next Semester),Branch,Course Allocated,Sem
0,vijesh.hingu@spit.ac.in,Vijesh Mitesh Hingu,2021300042,TY Sem VI (TE_No Intership students only),COMP,ASTITVA,6
1,dhruvil.doshi@spit.ac.in,Dhruvil Doshi,2021300027,TY Sem VI (TE_No Intership students only),COMP,ASTITVA,6
2,aditya.choudhary@spit.ac.in,Aditya Choudhary,2021300022,TY Sem VI (TE_No Intership students only),COMP,ASTITVA,6
3,kunal.bhatia@spit.ac.in,Kunal Bhatia,2021300010,TY Sem VI (TE_No Intership students only),COMP,ASTITVA,6
4,ameya.dabholkar@spit.ac.in,Ameya Dabholkar,2021300023,TY Sem VI (TE_No Intership students only),COMP,ASTITVA,6
5,siddhant.rao@spit.ac.in,Siddhant Paritosh Rao,2021600055,TY Sem VI (TE_No Intership students only),CSE-AIML,ASTITVA,6
6,rahul.shinde@spit.ac.in,rahul shinde,2021600061,TY Sem VI (TE_No Intership students only),CSE-AIML,ASTITVA,6
7,vansh.talwar@spit.ac.in,Vansh Talwar,2021600064,TY Sem VI (TE_No Intership students only),CSE-AIML,ASTITVA,6
8,divya.raichura@spit.ac.in,Divya Raichura,2021600052,TY Sem VI (TE_No Intership students only),CSE-AIML,ASTITVA,6
9,aditya.kadam@spit.ac.in,Aditya Kadam,2021200046,TY Sem VI (TE_No Intership students only),EXTC,ASTITVA,6
10,mohammedmaaz.khan22@spit.ac.in,Mohammed Maaz khan,2022201010,TY Sem VI (TE_No Intership students only),EXTC,ASTITVA,6
11,lokesh.chaudhari22@spit.ac.in,lokesh chauadhari,2022300014,SY Sem IV,COMP,ASTITVA,4
12,swayam.sawant22@spit.ac.in,Swayam Sawant,2022300102,SY Sem IV,COMP,ASTITVA,4
13,komal.sali23@spit.ac.in,Komal Sali,2023601008,SY Sem IV,CSE-AIML,ASTITVA,4
14,shrikant.kabade23@spit.ac.in,kabade shrikant gopinath,2023701002,SY Sem IV,CSE-DS,ASTITVA,4
15,shashvat.sangle22@spit.ac.in,SANGLE SHASHVAT DIGVIJAY,2022200103,SY Sem IV,EXTC,ASTITVA,4
16,harsh.b.pandey22@spit.ac.in,Pandey Harsh Balkrishna,2022200086,SY Sem IV,EXTC,ASTITVA,4
17,vishwas.tripathi22@spit.ac.in,TRIPATHI VISHWAS SANTOSH,2022200122,SY Sem IV,EXTC,ASTITVA,4
18,aditi.rao22@spit.ac.in,Aditi Rao,2022200003,SY Sem IV,EXTC,ASTITVA,4
19,adya.jha22@spit.ac.in,Jha Adya,2022200054,SY Sem IV,EXTC,ASTITVA,4
20,yash.sharma23@spit.ac.in,YASH LALIT SHARMA,2023300220,FY Sem II,COMP,ASTITVA,2
21,omkar.jadhav23@spit.ac.in,Omkar Pandurang Jadhav,2023300082,FY Sem II,COMP,ASTITVA,2
22,vishwajit.sarnobat23@spit.ac.in,Vishwajit Sarnobat,2023300195,FY Sem II,COMP,ASTITVA,2
23,lalit.mahajan23@spit.ac.in,Mahajan Lalit HIraman,2023300133,FY Sem II,COMP,ASTITVA,2
24,preetish.kulkarni23@spit.ac.in,Kulkarni Preetish Jayant,2023300125,FY Sem II,COMP,ASTITVA,2
25,soham.ghorpade23@spit.ac.in,Soham Amol Ghorpade,2023300064,FY Sem II,COMP,ASTITVA,2
26,vinayak.yadav23@spit.ac.in,Vinayak Chandrashekhar Yadav,2023300264,FY Sem II,COMP,ASTITVA,2
27,krish.sodhi23@spit.ac.in,Krish Sodhi,2023300233,FY Sem II,COMP,ASTITVA,2
28,prathmesh.mohite23@spit.ac.in,Prathmesh Babasaheb Mohite,2023300151,FY Sem II,COMP,ASTITVA,2
29,asmiya.sayyad23@spit.ac.in,Asmiya Kadir Sayyad,2023300198,FY Sem II,COMP,ASTITVA,2
30,aayush.shah23@spit.ac.in,Aayush Pritesh Shah,2023300201,FY Sem II,COMP,ASTITVA,2
31,meet.mehta23@spit.ac.in,Meet Bhavin Mehta,2023300140,FY Sem II,COMP,ASTITVA,2
32,aryan.gorde23@spit.ac.in,GORDE ARYAN HITESH,2023300068,FY Sem II,COMP,ASTITVA,2
33,siddh.jain23@spit.ac.in,Siddh Jain,2023800039,FY Sem II,CSE,ASTITVA,2
34,aryan.babar23@spit.ac.in,Aryan Babar,2023200009,FY Sem II,EXTC,ASTITVA,2
35,gauravsingh.sisodia23@spit.ac.in,Sisodia Gauravsingh Jaipalsingh,2023200116,FY Sem II,EXTC,ASTITVA,2
36,atharv.dhage23@spit.ac.in,Dhage Atharv Ramesh,2023200035,FY Sem II,EXTC,ASTITVA,2
37,abhijit.shirke23@spit.ac.in,Abhijit Namdeo Shirke,2023510054,FY Sem II (MCA),MCA,ASTITVA,2
38,yash.rautela23@spit.ac.in,Yash Rautela,2023510047,FY Sem II (MCA),MCA,ASTITVA,2
39,shubhankar.shinde23@spit.ac.in,SHUBHANKAR PRAVIN SHINDE,2023510053,FY Sem II,MCA,ASTITVA,2

In [45]:
final = pd.DataFrame(columns=['email', 'name', 'uid', 'branch', 'sem', 'course'])
for sheet_no in range(1, 33): # skipping nptel sheet
    df = pd.read_excel(os.path.join(data_dir, 'even sem 2023-24.xlsx'), sheet_name=sheet_no)
    df.columns = ['email', 'name', 'uid', 'class', 'branch', 'course', 'sem']
    df.drop(columns=['class'], inplace=True)
    df = df[['email', 'name', 'uid', 'branch', 'sem', 'course']]
    final = pd.concat([final, df], ignore_index=True)

In [46]:
final.isnull().sum()

email     0
name      0
uid       0
branch    0
sem       0
course    0
dtype: int64

In [47]:
final.head(10)

,email,name,uid,branch,sem,course
0,vijesh.hingu@spit.ac.in,Vijesh Mitesh Hingu,2021300042,COMP,6,ASTITVA
1,dhruvil.doshi@spit.ac.in,Dhruvil Doshi,2021300027,COMP,6,ASTITVA
2,aditya.choudhary@spit.ac.in,Aditya Choudhary,2021300022,COMP,6,ASTITVA
3,kunal.bhatia@spit.ac.in,Kunal Bhatia,2021300010,COMP,6,ASTITVA
4,ameya.dabholkar@spit.ac.in,Ameya Dabholkar,2021300023,COMP,6,ASTITVA
5,siddhant.rao@spit.ac.in,Siddhant Paritosh Rao,2021600055,CSE-AIML,6,ASTITVA
6,rahul.shinde@spit.ac.in,rahul shinde,2021600061,CSE-AIML,6,ASTITVA
7,vansh.talwar@spit.ac.in,Vansh Talwar,2021600064,CSE-AIML,6,ASTITVA
8,divya.raichura@spit.ac.in,Divya Raichura,2021600052,CSE-AIML,6,ASTITVA
9,aditya.kadam@spit.ac.in,Aditya Kadam,2021200046,EXTC,6,ASTITVA

In [48]:
final.shape

(1742, 6)

In [8]:
final.to_csv(os.path.join(data_dir, 'sheet-4.csv'), index=False)

In [49]:
final.sort_values(by=['course', 'sem', 'branch', 'uid'])

,email,name,uid,branch,sem,course
25,soham.ghorpade23@spit.ac.in,Soham Amol Ghorpade,2023300064,COMP,2,ASTITVA
32,aryan.gorde23@spit.ac.in,GORDE ARYAN HITESH,2023300068,COMP,2,ASTITVA
21,omkar.jadhav23@spit.ac.in,Omkar Pandurang Jadhav,2023300082,COMP,2,ASTITVA
24,preetish.kulkarni23@spit.ac.in,Kulkarni Preetish Jayant,2023300125,COMP,2,ASTITVA
23,lalit.mahajan23@spit.ac.in,Mahajan Lalit HIraman,2023300133,COMP,2,ASTITVA
...,...,...,...,...,...,...
1702,akshat.biniwale@spit.ac.in,Akshat Biniwale,2021300014,COMP,6,yoga 1
1701,dewyani.deshmukh@spit.ac.in,dewyani.deshmukh@spit.ac.in,2021300024,COMP,6,yoga 1
1704,ajay.lohar@spit.ac.in,Ajay Sohanlal Lohar,2021200064,EXTC,6,yoga 1
1703,aryan.adav22@spit.ac.in,Aryan Ambarish Adav,2022201001,EXTC,6,yoga 1
1705,nilesh.admane22@spit.ac.in,Nilesh Sahebrao Admane,2022201002,EXTC,6,yoga 1

In [29]:
courses = pd.read_csv(os.path.join(data_dir, 'courses.csv'))
course_names = courses['course_name'].tolist()
course_names

['Art of living',
 'Introduction to Bhagvadgita',
 'Pranvidya',
 'Yog Vidya',
 'Mentoring School Children (Abhyudaya)',
 'Mentorship to Juniors',
 'NSS',
 'Principle Centered Leadership',
 'Teaching Assistantship',
 'Terrace Gardening',
 "Volunteering at Dr. Amte's Anandvan",
 'Wall Painting',
 'Working with NGO',
 'Astitva',
 'Kathak',
 'Physical Fitness',
 'Running',
 'Self Defense for Women',
 'Skipping',
 'Sports',
 'Staircase Climbing',
 'Swimming',
 'Taekwondo',
 'Trekking',
 'Basic Cooking',
 'Basics of Fire Safety',
 'Basics of Keyboard playing',
 'Basics of Music Composition',
 'Design Thinking',
 'Film Appreciation',
 'Fundamentals of Photography',
 'Idea Lab',
 'Indian Knowledge System',
 'Innovation and Creativity',
 'Read a book',
 'Short Film Making/ Cinematography',
 'Social Psychology',
 'Study of Life',
 'Technology Entrepreneurship',
 'Integrated Personality Development',
 'Jeevan Vidya (Work Life Balance)',
 'Universal Human Value']

After cleaning some data in excel, normalizing rest of the courses:

In [33]:
sheet4 = pd.read_csv(os.path.join(data_dir, 'sheet-4.csv'))

In [34]:
sheet4['course'].unique()

array(['Astitva', 'Introduction to Bhagvad Gita',
       'Introduction to Bhagvadgita', 'Introduction to Bhagvatgita',
       'Introduction to Bhagwadgita', 'Introduction To Bhagvadgita',
       'Introduction to Bhagwad Gita', 'Introduction to bhagwadgita',
       'Introduction to Bhagavad GIta', 'Introduction to Bhagavadgita',
       'Introduction of Baghvadgita', 'Bhagwan Gita',
       'Introduction to Bhagvadgita (limit 50 students)', 'Read a book',
       'read a book', 'Basic Cooking', 'Design Thinking',
       'Design thinking', 'Film Appreciation', 'Basics of Fire Safety',
       'Innovation and Creativity', 'Integrated Personality Development',
       'Mentoring School Children (Abhyudaya)',
       'Mentoring School Children (Abhyudaya) ', 'Working with NGO',
       'Fundamentals of Photography', 'Pranvidya', 'pranvidya', 'Running',
       'running', 'Self Defense for Women', 'self Defense for Women',
       'Skipping', 'Skipping ', 'skipiing', 'Sports',
       'Sports-Push ups/Surya Namaskar', 'Sports-Push ups',
       'Sports Push ups', 'Staircase Climbing', 'Staircase Climbing.',
       'Study of Life', 'study of Life', 'Taekwondo',
       "Volunteering at Dr. Amte's Anandvan", 'Wall Painting',
       'Art of living', 'Yog Vidya'], dtype=object)

In [35]:
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

['Introduction to Bhagvad Gita',
 'Introduction to Bhagvatgita',
 'Introduction to Bhagwadgita',
 'Introduction To Bhagvadgita',
 'Introduction to Bhagwad Gita',
 'Introduction to bhagwadgita',
 'Introduction to Bhagavad GIta',
 'Introduction to Bhagavadgita',
 'Introduction of Baghvadgita',
 'Bhagwan Gita',
 'Introduction to Bhagvadgita (limit 50 students)',
 'read a book',
 'Design thinking',
 'Mentoring School Children (Abhyudaya) ',
 'pranvidya',
 'running',
 'self Defense for Women',
 'Skipping ',
 'skipiing',
 'Sports-Push ups/Surya Namaskar',
 'Sports-Push ups',
 'Sports Push ups',
 'Staircase Climbing.',
 'study of Life']

These names have to be the same as that in courses.csv

In [36]:
course_names

['Art of living',
 'Introduction to Bhagvadgita',
 'Pranvidya',
 'Yog Vidya',
 'Mentoring School Children (Abhyudaya)',
 'Mentorship to Juniors',
 'NSS',
 'Principle Centered Leadership',
 'Teaching Assistantship',
 'Terrace Gardening',
 "Volunteering at Dr. Amte's Anandvan",
 'Wall Painting',
 'Working with NGO',
 'Astitva',
 'Kathak',
 'Physical Fitness',
 'Running',
 'Self Defense for Women',
 'Skipping',
 'Sports',
 'Staircase Climbing',
 'Swimming',
 'Taekwondo',
 'Trekking',
 'Basic Cooking',
 'Basics of Fire Safety',
 'Basics of Keyboard playing',
 'Basics of Music Composition',
 'Design Thinking',
 'Film Appreciation',
 'Fundamentals of Photography',
 'Idea Lab',
 'Indian Knowledge System',
 'Innovation and Creativity',
 'Read a book',
 'Short Film Making/ Cinematography',
 'Social Psychology',
 'Study of Life',
 'Technology Entrepreneurship',
 'Integrated Personality Development',
 'Jeevan Vidya (Work Life Balance)',
 'Universal Human Value']

In [37]:
sheet4['course'] = sheet4['course'].map(lambda x: 'Introduction to Bhagvadgita' if x.lower().startswith('introduction') else x)
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

['Bhagwan Gita',
 'read a book',
 'Design thinking',
 'Mentoring School Children (Abhyudaya) ',
 'pranvidya',
 'running',
 'self Defense for Women',
 'Skipping ',
 'skipiing',
 'Sports-Push ups/Surya Namaskar',
 'Sports-Push ups',
 'Sports Push ups',
 'Staircase Climbing.',
 'study of Life']

In [38]:
sheet4['course'] = sheet4['course'].str[0].map(lambda x: x.upper()).values + sheet4['course'].str[1:]
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

['Bhagwan Gita',
 'Design thinking',
 'Mentoring School Children (Abhyudaya) ',
 'Skipping ',
 'Skipiing',
 'Sports-Push ups/Surya Namaskar',
 'Sports-Push ups',
 'Sports Push ups',
 'Staircase Climbing.']

In [39]:
sheet4['course'] = sheet4['course'].str.strip()
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

['Bhagwan Gita',
 'Design thinking',
 'Skipiing',
 'Sports-Push ups/Surya Namaskar',
 'Sports-Push ups',
 'Sports Push ups',
 'Staircase Climbing.']

In [40]:
sheet4['course'] = sheet4['course'].map(lambda x: 'Sports' if x.lower().startswith('sports') else x)
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

['Bhagwan Gita', 'Design thinking', 'Skipiing', 'Staircase Climbing.']

In [41]:
def normalize(course_name):
    if course_name == 'Design thinking':
        return 'Design Thinking'
    if course_name == 'Skipiing':
        return 'Skipping'
    if course_name == 'Staircase Climbing.':
        return 'Staircase Climbing'
    if course_name == 'Bhagwan Gita':
        return 'Introduction to Bhagvadgita'
    return course_name

sheet4['course'] = sheet4['course'].map(normalize)
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

[]

In [ ]:
sheet4['name'] = sheet4['name'].map(lambda x: x.strip().title())

In [51]:
sheet4.head(20)

,email,name,uid,branch,sem,course
0,vijesh.hingu@spit.ac.in,Vijesh Mitesh Hingu,2021300042,COMP,6,Astitva
1,dhruvil.doshi@spit.ac.in,Dhruvil Doshi,2021300027,COMP,6,Astitva
2,aditya.choudhary@spit.ac.in,Aditya Choudhary,2021300022,COMP,6,Astitva
3,kunal.bhatia@spit.ac.in,Kunal Bhatia,2021300010,COMP,6,Astitva
4,ameya.dabholkar@spit.ac.in,Ameya Dabholkar,2021300023,COMP,6,Astitva
5,siddhant.rao@spit.ac.in,Siddhant Paritosh Rao,2021600055,CSE-AIML,6,Astitva
6,rahul.shinde@spit.ac.in,Rahul Shinde,2021600061,CSE-AIML,6,Astitva
7,vansh.talwar@spit.ac.in,Vansh Talwar,2021600064,CSE-AIML,6,Astitva
8,divya.raichura@spit.ac.in,Divya Raichura,2021600052,CSE-AIML,6,Astitva
9,aditya.kadam@spit.ac.in,Aditya Kadam,2021200046,EXTC,6,Astitva
10,mohammedmaaz.khan22@spit.ac.in,Mohammed Maaz Khan,2022201010,EXTC,6,Astitva
11,lokesh.chaudhari22@spit.ac.in,Lokesh Chauadhari,2022300014,COMP,4,Astitva
12,swayam.sawant22@spit.ac.in,Swayam Sawant,2022300102,COMP,4,Astitva
13,komal.sali23@spit.ac.in,Komal Sali,2023601008,CSE-AIML,4,Astitva
14,shrikant.kabade23@spit.ac.in,Kabade Shrikant Gopinath,2023701002,CSE-DS,4,Astitva
15,shashvat.sangle22@spit.ac.in,Sangle Shashvat Digvijay,2022200103,EXTC,4,Astitva
16,harsh.b.pandey22@spit.ac.in,Pandey Harsh Balkrishna,2022200086,EXTC,4,Astitva
17,vishwas.tripathi22@spit.ac.in,Tripathi Vishwas Santosh,2022200122,EXTC,4,Astitva
18,aditi.rao22@spit.ac.in,Aditi Rao,2022200003,EXTC,4,Astitva
19,adya.jha22@spit.ac.in,Jha Adya,2022200054,EXTC,4,Astitva

In [55]:
sheet4.sort_values(by=['course', 'sem', 'branch', 'uid'], ascending=True, inplace=True)
sheet4.head(20)

,email,name,uid,branch,sem,course
1691,namrata.dalvi23@spit.ac.in,Namrata Dalvi,2023300035,COMP,2,Art of living
1686,ayush.deore23@spit.ac.in,Deore Ayush Nitin,2023300043,COMP,2,Art of living
1687,kimaya.dixit23@spit.ac.in,Kimaya Yatin Dixit,2023300049,COMP,2,Art of living
1692,sneha.jain23@spit.ac.in,Sneha Jain,2023300089,COMP,2,Art of living
1693,grishma.jetani23@spit.ac.in,Jetani Grishma Jayeshbhai,2023300094,COMP,2,Art of living
1688,amruta.johare23@spit.ac.in,Amruta Johare,2023300095,COMP,2,Art of living
1694,srushti.khade23@spit.ac.in,Srushti Sachin Khade,2023300112,COMP,2,Art of living
1685,abhinav.khajurgi23@spit.ac.in,Khajurgi Abhinav Shashidhar,2023300113,COMP,2,Art of living
1695,rasika.kinhikar23@spit.ac.in,Kinhikar Rasika Ajay,2023300119,COMP,2,Art of living
1684,darsh.kothari23@spit.ac.in,Kothari Darsh Amit,2023300123,COMP,2,Art of living
1690,sania.rakhangi23@spit.ac.in,Sania Mohammed Irfan Rakhangi,2023300180,COMP,2,Art of living
1689,heet.shah123@spit.ac.in,Heet Keyur Shah,2023300208,COMP,2,Art of living
1696,onkar.allewar23@Spiit.ac.in,Onkar Allewar,2023800004,CSE,2,Art of living
1697,shivprasad.chougule23@spit.ac.in,Chougule Shivprasad Annasaheb,2023200026,EXTC,2,Art of living
1699,shravani.dhebe23@spit.ac.in,Shravani Dattatray Dhebe,2023200036,EXTC,2,Art of living
1700,kartik.rane23@spit.ac.in,Rane Kartik Santosh,2023200093,EXTC,2,Art of living
1698,atharv.bodake23@spit.ac.in,Atharv Bodake,2023800021,EXTC,2,Art of living
1683,atanu.debnath23@spit.ac.in,Atanu Debnath,2023510014,MCA,2,Art of living
1681,soham.ghaisas22@spit.ac.in,Ghaisas Soham Shailesh,2022200041,EXTC,4,Art of living
1682,aditya.nagane23@spit.ac.in,Aditya Pramod Nagane,2023201001,EXTC,4,Art of living

In [56]:
sheet4.to_csv(os.path.join(data_dir, 'sheet-4.csv'), index=False)

In [18]:
sheet4 = pd.read_csv(os.path.join(data_dir, 'sheet-4.csv'))

Deleting duplicate rows:

In [4]:
print(f'Number of duplicate rows: {sheet4.duplicated().sum()} / {sheet4.shape[0]}')

Number of duplicate rows: 10 / 1742

In [5]:
sheet4.loc[sheet4.duplicated(), :]

,email,name,uid,branch,sem,course
570,tisha.parmar23@spit.ac.in,Tisha Parmar,2023300161,COMP,2,Mentoring School Children (Abhyudaya)
585,priyal.jakhotia23@spit.ac.in,Priyal Yogesh Jakhotia,2023200062,EXTC,2,Mentoring School Children (Abhyudaya)
690,mayank.nichlani22@spit.ac.in,Nichlani Mayank Sagar,2022700035,CSE-DS,4,Read a book
958,anish.gade@spit.ac.in,Anish Gade,2021700022,CSE-DS,6,Skipping
1037,vepul.bhanuse23@spit.ac.in,Vepul Bhanuse,2023510004,MCA,2,Sports
1197,yash.patil23@spit.ac.in,Yash Arun Patil,2023300172,COMP,2,Staircase Climbing
1276,rishi.sharma23@spit.ac.in,Sharma Rishi Sanjay,2023200109,EXTC,2,Staircase Climbing
1291,niketan.gawade23@spit.ac.in,Niketan Gawade,2023510023,MCA,2,Staircase Climbing
1425,meetesh.bhandarkar@spit.ac.in,Meetesh Bhandarkar,2021200011,EXTC,6,Staircase Climbing
1584,suyash.bargal@spit.ac.in,Suyash Anil Bargal,2021201075,EXTC,8,Volunteering at Dr. Amte's Anandvan

In [6]:
sheet4.drop_duplicates(inplace=True, keep='first', ignore_index=True)

In [8]:
sheet4.shape[0]

1732

In [9]:
sheet4.to_csv(os.path.join(data_dir, 'sheet-4.csv'), index=False)

Checking for duplicates based on email:

In [10]:
sheet4.duplicated(subset=['email']).sum()

42

In [19]:
duplicate_emails = set(sheet4['email'][sheet4.duplicated(subset=['email'])].values)
duplicated_rows = sheet4[sheet4['email'].map(lambda x: x in duplicate_emails)].sort_values(by='email')
duplicated_rows

,email,name,uid,branch,sem,course
1563,aaryan.vaidya@spit.ac.in,Aaryan Vaidya,2020100062,ETRX,8,Taekwondo
969,aaryan.vaidya@spit.ac.in,Aaryan Vaidya,2020100062,ETRX,8,Skipping
1651,aayush.mewada23@spit.ac.in,Aayush Mewada,2023300146,COMP,2,Working with NGO
1184,aayush.mewada23@spit.ac.in,Aayush Mewada,2023300146,COMP,2,Staircase Climbing
179,aditya.salunke22@spit.ac.in,Salunke Aditya Rajendra,2022510053,MCA,4,Design Thinking
...,...,...,...,...,...,...
1337,vedant.mankar22@spit.ac.in,Vedant Manohar Mankar,2022200126,EXTC,4,Staircase Climbing
922,vinay.racha22@spit.ac.in,Vinay Racha,2022600045,CSE-AIML,4,Skipping
1716,vinay.racha22@spit.ac.in,Vinay Racha,2022600045,CSE-AIML,4,Yog Vidya
1201,yash.sonawane23@spit.ac.in,Yash Chandramani Sonawane,2023300235,COMP,2,Staircase Climbing
780,yash.sonawane23@spit.ac.in,Yash Chandramani Sonawane,2023300235,COMP,2,Running

In [21]:
duplicated_rows.to_csv(os.path.join(data_dir, 'sheet-4-duplicated-rows.csv'), index=False)

Joiining with the courses df:

In [4]:
sheet4 = pd.read_csv(os.path.join(data_dir, 'sheet-4.csv'))
cols_to_keep = list(sheet4.columns) + ['category']
sheet4 = pd.merge(sheet4, courses, left_on='course', right_on='course_name')[cols_to_keep]
sheet4

,email,name,uid,branch,sem,course,category
0,namrata.dalvi23@spit.ac.in,Namrata Dalvi,2023300035,COMP,2,Art of living,Spiritual
1,ayush.deore23@spit.ac.in,Deore Ayush Nitin,2023300043,COMP,2,Art of living,Spiritual
2,kimaya.dixit23@spit.ac.in,Kimaya Yatin Dixit,2023300049,COMP,2,Art of living,Spiritual
3,sneha.jain23@spit.ac.in,Sneha Jain,2023300089,COMP,2,Art of living,Spiritual
4,grishma.jetani23@spit.ac.in,Jetani Grishma Jayeshbhai,2023300094,COMP,2,Art of living,Spiritual
...,...,...,...,...,...,...,...
1724,akshat.biniwale@spit.ac.in,Akshat Biniwale,2021300014,COMP,6,Yog Vidya,Spiritual
1725,dewyani.deshmukh@spit.ac.in,Dewyani.Deshmukh@Spit.Ac.In,2021300024,COMP,6,Yog Vidya,Spiritual
1726,ajay.lohar@spit.ac.in,Ajay Sohanlal Lohar,2021200064,EXTC,6,Yog Vidya,Spiritual
1727,aryan.adav22@spit.ac.in,Aryan Ambarish Adav,2022201001,EXTC,6,Yog Vidya,Spiritual
1728,nilesh.admane22@spit.ac.in,Nilesh Sahebrao Admane,2022201002,EXTC,6,Yog Vidya,Spiritual

In [5]:
sheet4.to_csv(os.path.join(data_dir, 'sheet-4.csv'), index=False)