Concatenating all excel sheets in a single CSV file (for even sem 23-24):

In [1]:
import pandas as pd
import os
data_dir = r'..\data'

Courses:

In [2]:
courses = pd.read_csv(os.path.join(data_dir, 'courses.csv'))
courses

    course_id                            course_name      category
0           1                          Art of living     Spiritual
1           2            Introduction to Bhagvadgita     Spiritual
2           3                              Pranvidya     Spiritual
3           4                              Yog Vidya     Spiritual
4           5  Mentoring School Children (Abhyudaya)        Social
5           6                  Mentorship to Juniors        Social
6           7                                    NSS        Social
7           8          Principle Centered Leadership        Social
8           9                 Teaching Assistantship        Social
9          10                      Terrace Gardening        Social
10         11    Volunteering at Dr. Amte's Anandvan        Social
11         12                          Wall Painting        Social
12         13                       Working with NGO        Social
13         14                                Astitva      Physical
14         15                                 Kathak      Physical
15         16                       Physical Fitness      Physical
16         17                                Running      Physical
17         18                 Self Defense for Women      Physical
18         19                               Skipping      Physical
19         20                                 Sports      Physical
20         21                     Staircase Climbing      Physical
21         22                               Swimming      Physical
22         23                              Taekwondo      Physical
23         24                               Trekking      Physical
24         25                          Basic Cooking  Intellectual
25         26                  Basics of Fire Safety  Intellectual
26         27             Basics of Keyboard playing  Intellectual
27         28            Basics of Music Composition  Intellectual
28         29                        Design Thinking  Intellectual
29         30                      Film Appreciation  Intellectual
30         31            Fundamentals of Photography  Intellectual
31         32                               Idea Lab  Intellectual
32         33                Indian Knowledge System  Intellectual
33         34              Innovation and Creativity  Intellectual
34         35                            Read a book  Intellectual
35         36                         Cinematography  Intellectual
36         37                      Social Psychology  Intellectual
37         38                          Study of Life  Intellectual
38         39            Technology Entrepreneurship  Intellectual
39         40     Integrated Personality Development     Emotional
40         41       Jeevan Vidya (Work Life Balance)     Emotional
41         42                  Universal Human Value     Emotional

In [9]:
course_names = courses['course_name']

Loading even sem 22-23.xlsx:

In [6]:
df = pd.read_excel(os.path.join(data_dir, 'even sem 2022-23.xlsx'), sheet_name=1)

In [20]:
df.head(10)

,email,name,uid,branch,sem,course
0,navinder.singh@spit.ac.in,Navinder Singh,2020200058,EXTC,7,Basic Cooking
1,madhura.chitale@spit.ac.in,Chitale Madhura Ramkrishna,2020300005,COMP,7,Basic Cooking
2,aakanksha.dhawale@spit.ac.in,Aakanksha Dhawale,2020300008,COMP,7,Basic Cooking
3,srushti.haryan@spit.ac.in,Haryan Srushti Manvendra,2020300018,COMP,7,Basic Cooking
4,manushree.dubey@spit.ac.in,Manushree Dubey,2020300010,COMP,7,Basic Cooking
5,kunal.thakur@spit.ac.in,Kunal Thakur,2020200060,EXTC,7,Basic Cooking
6,prathamesh.redij@spit.ac.in,Prathamesh Sanjay Redij,2020300058,COMP,7,Basic cooking
7,krish.shah@spit.ac.in,Krish Shah,2020300061,COMP,7,Basic cooking
8,shivalik.pandita@spit.ac.in,Shivalik Pandita,2020300049,COMP,7,Basic cooking
9,arnav.joglekar22@spit.ac.in,Arnav Ajay Joglekar,2022600002,CSE-AIML,3,Basic cooking

In [23]:
final = pd.DataFrame(columns=['email', 'name', 'uid', 'branch', 'sem', 'course'])
for sheet_no in range(21): 
    df = pd.read_excel(os.path.join(data_dir, 'even sem 2022-23.xlsx'), sheet_name=sheet_no, usecols=['Email Address', 'Name (as in the college records)', 'UID No.', 'Class (to be entered in next Semester)', 'Branch', 'SEVA/SATVA Course Name', 'Sem'])
    df.columns = ['email', 'name', 'uid', 'class', 'branch', 'course', 'sem']
    df.drop(columns=['class'], inplace=True)
    df = df[['email', 'name', 'uid', 'branch', 'sem', 'course']]
    final = pd.concat([final, df], ignore_index=True)

In [29]:
final.isnull().sum()

email     0
name      0
uid       0
branch    0
sem       0
course    0
dtype: int64

In [30]:
final.shape

(1122, 6)

In [31]:
final.head(10)

,email,name,uid,branch,sem,course
0,rajyavardhan.padvi@spit.ac.in,Rajyavardhan Suresh Padvi,2021300087,COMP,4,Yog Vidya
1,mahesh.patil@spit.ac.in,Mahesh Anil Patil,2021300095,COMP,4,Yog Vidya
2,arshad.mapari@spit.ac.in,Arshad Husenmiya Mapari,2021600043,CSE-AIML,4,Yog Vidya
3,pavan.gole22@spit.ac.in,Pavan Ratan Gole,2022601003,CSE-AIML,4,Yog Vidya
4,rohan.warghade@spit.ac.in,ROHAN JANARDHAN WARGHADE,2021600071,CSE-AIML,4,Yog Vidya
5,kenneth.rodrigues.22@spit.ac.in,Kenneth David Rodrigues,2022701008,CSE-DS,4,Yog Vidya
6,trupti.g@spit.ac.in,Trupti Gopinath,2018120059,EXTC,8,Yog Vidya
7,abhieram.bandaru@spit.ac.in,Abhieram Bandaru,2021200006,EXTC,4,Yog Vidya
8,vineet.pundpal22@spit.ac.in,Vineet Pundpal,2022201018,EXTC,4,Yog Vidya
9,roshani.patel22@spit.ac.in,PATEL ROSHANI RAJDHAR,2022201014,EXTC,4,Yog Vidya

In [32]:
final.to_csv(os.path.join(data_dir, 'sheet-2.csv'), index=False)

In [34]:
courses = pd.read_csv(os.path.join(data_dir, 'courses.csv'))
course_names = courses['course_name'].tolist()
course_names

['Art of living',
 'Introduction to Bhagvadgita',
 'Pranvidya',
 'Yog Vidya',
 'Mentoring School Children (Abhyudaya)',
 'Mentorship to Juniors',
 'NSS',
 'Principle Centered Leadership',
 'Teaching Assistantship',
 'Terrace Gardening',
 "Volunteering at Dr. Amte's Anandvan",
 'Wall Painting',
 'Working with NGO',
 'Astitva',
 'Kathak',
 'Physical Fitness',
 'Running',
 'Self Defense for Women',
 'Skipping',
 'Sports',
 'Staircase Climbing',
 'Swimming',
 'Taekwondo',
 'Trekking',
 'Basic Cooking',
 'Basics of Fire Safety',
 'Basics of Keyboard playing',
 'Basics of Music Composition',
 'Design Thinking',
 'Film Appreciation',
 'Fundamentals of Photography',
 'Idea Lab',
 'Indian Knowledge System',
 'Innovation and Creativity',
 'Read a book',
 'Short Film Making/ Cinematography',
 'Social Psychology',
 'Study of Life',
 'Technology Entrepreneurship',
 'Integrated Personality Development',
 'Jeevan Vidya (Work Life Balance)',
 'Universal Human Value']

After cleaning some data in excel, normalizing rest of the courses:

In [35]:
sheet2 = pd.read_csv(os.path.join(data_dir, 'sheet-2.csv'))
sheet2['course'].unique()

array(['Yog Vidya', 'Read a book', ' Read a book ', 'Study of book',
       'Basics of Fire Safety', 'Basics of Fire Safety ', 'Idea Lab',
       'Idea Lab(Prayas)', 'IdeaLab(Prayas)', 'Trekking',
       'Integrated Personality Development',
       'Integrated Personality Development ', 'Teaching Assistantship',
       'Teaching Assistantship ', 'Working with NGO', 'Working with NGO ',
       ' Working in NGO ', 'Sports', 'NSS', 'NSS camp',
       'NSS (4 Days Camp)', 'Nss', 'Nss ', '31. NSS (4 Days Camp)',
       'Film Appreciation', 'Film appreciation ', 'Film Appreciation ',
       ' Film Appreciation', 'Movie review', 'Fim appreciation',
       'Flim Appreciation ', 'Running', ' Sports', 'Sports ', 'Skipping',
       'Trek', 'Swimming ', 'Mentorship to Juniors',
       'mentorship to juniors', 'Basics of Keyboard  Playing',
       'Basics of Keyboard playing', 'Basics of Keyboard Playing',
       'Basics of keyboard playing', 'Basics of Keyboard Playing ',
       'Basics of Music Composition ', 'Basic Cooking', 'Design Thinking',
       'Design Thinking ', ' Design Thinking',
       'Innovation and Creativity', 'Innovation and Creativity ',
       'Innovation and creativity ', 'Technology Entrepreneurship',
       'Mentoring School Children (Abhyudaya)'], dtype=object)

In [36]:
not_matching = [i for i in sheet2['course'].unique() if i not in course_names]
not_matching

[' Read a book ',
 'Study of book',
 'Basics of Fire Safety ',
 'Idea Lab(Prayas)',
 'IdeaLab(Prayas)',
 'Integrated Personality Development ',
 'Teaching Assistantship ',
 'Working with NGO ',
 ' Working in NGO ',
 'NSS camp',
 'NSS (4 Days Camp)',
 'Nss',
 'Nss ',
 '31. NSS (4 Days Camp)',
 'Film appreciation ',
 'Film Appreciation ',
 ' Film Appreciation',
 'Movie review',
 'Fim appreciation',
 'Flim Appreciation ',
 ' Sports',
 'Sports ',
 'Trek',
 'Swimming ',
 'mentorship to juniors',
 'Basics of Keyboard  Playing',
 'Basics of Keyboard Playing',
 'Basics of keyboard playing',
 'Basics of Keyboard Playing ',
 'Basics of Music Composition ',
 'Design Thinking ',
 ' Design Thinking',
 'Innovation and Creativity ',
 'Innovation and creativity ']

These names have to be the same as that in courses.csv

In [37]:
course_names

['Art of living',
 'Introduction to Bhagvadgita',
 'Pranvidya',
 'Yog Vidya',
 'Mentoring School Children (Abhyudaya)',
 'Mentorship to Juniors',
 'NSS',
 'Principle Centered Leadership',
 'Teaching Assistantship',
 'Terrace Gardening',
 "Volunteering at Dr. Amte's Anandvan",
 'Wall Painting',
 'Working with NGO',
 'Astitva',
 'Kathak',
 'Physical Fitness',
 'Running',
 'Self Defense for Women',
 'Skipping',
 'Sports',
 'Staircase Climbing',
 'Swimming',
 'Taekwondo',
 'Trekking',
 'Basic Cooking',
 'Basics of Fire Safety',
 'Basics of Keyboard playing',
 'Basics of Music Composition',
 'Design Thinking',
 'Film Appreciation',
 'Fundamentals of Photography',
 'Idea Lab',
 'Indian Knowledge System',
 'Innovation and Creativity',
 'Read a book',
 'Short Film Making/ Cinematography',
 'Social Psychology',
 'Study of Life',
 'Technology Entrepreneurship',
 'Integrated Personality Development',
 'Jeevan Vidya (Work Life Balance)',
 'Universal Human Value']

Stripping leading and trailing spaces:

In [38]:
sheet2['course'] = sheet2['course'].str.strip()
not_matching = [i for i in sheet2['course'].unique() if i not in course_names]
not_matching

['Study of book',
 'Idea Lab(Prayas)',
 'IdeaLab(Prayas)',
 'Working in NGO',
 'NSS camp',
 'NSS (4 Days Camp)',
 'Nss',
 '31. NSS (4 Days Camp)',
 'Film appreciation',
 'Movie review',
 'Fim appreciation',
 'Flim Appreciation',
 'Trek',
 'mentorship to juniors',
 'Basics of Keyboard  Playing',
 'Basics of Keyboard Playing',
 'Basics of keyboard playing',
 'Innovation and creativity']

NSS related issues:

In [39]:
sheet2['course'] = sheet2['course'].map(lambda x: 'NSS' if 'nss' in x.lower() else x)
not_matching = [i for i in sheet2['course'].unique() if i not in course_names]
not_matching

['Study of book',
 'Idea Lab(Prayas)',
 'IdeaLab(Prayas)',
 'Working in NGO',
 'Film appreciation',
 'Movie review',
 'Fim appreciation',
 'Flim Appreciation',
 'Trek',
 'mentorship to juniors',
 'Basics of Keyboard  Playing',
 'Basics of Keyboard Playing',
 'Basics of keyboard playing',
 'Innovation and creativity']

Keyboard playing:

In [40]:
sheet2['course'] = sheet2['course'].map(lambda x: 'Basics of Keyboard playing' if 'keyboard' in x.lower() else x)
not_matching = [i for i in sheet2['course'].unique() if i not in course_names]
not_matching

['Study of book',
 'Idea Lab(Prayas)',
 'IdeaLab(Prayas)',
 'Working in NGO',
 'Film appreciation',
 'Movie review',
 'Fim appreciation',
 'Flim Appreciation',
 'Trek',
 'mentorship to juniors',
 'Innovation and creativity']

Idea lab:

In [42]:
sheet2['course'] = sheet2['course'].map(lambda x: 'Idea Lab' if x.startswith('Idea') else x)
not_matching = [i for i in sheet2['course'].unique() if i not in course_names]
not_matching

['Study of book',
 'Working in NGO',
 'Film appreciation',
 'Movie review',
 'Fim appreciation',
 'Flim Appreciation',
 'Trek',
 'mentorship to juniors',
 'Innovation and creativity']

Film appreciation:

In [43]:
sheet2['course'] = sheet2['course'].map(lambda x: 'Film Appreciation' if 'appreciation' in x.lower() else x)
not_matching = [i for i in sheet2['course'].unique() if i not in course_names]
not_matching

['Study of book',
 'Working in NGO',
 'Movie review',
 'Trek',
 'mentorship to juniors',
 'Innovation and creativity']

In [44]:
def normalize(course_name):
    if course_name == 'Study of book':
        return 'Read a book'
    if course_name == 'Working in NGO':
        return 'Working with NGO'
    if course_name == 'Movie review':
        return 'Film Appreciation'
    if course_name == 'Trek':
        return 'Trekking'
    if course_name == 'mentorship to juniors':
        return 'Mentorship to Juniors'
    if course_name == 'Innovation and creativity':
        return 'Innovation and Creativity'
    return course_name

sheet2['course'] = sheet2['course'].map(normalize)
not_matching = [i for i in sheet2['course'].unique() if i not in course_names]
not_matching

[]

Converting all names to title case:

In [45]:
sheet2['name'] = sheet2['name'].map(lambda x: x.strip().title())

In [46]:
sheet2.head(20)

,email,name,uid,branch,sem,course
0,rajyavardhan.padvi@spit.ac.in,Rajyavardhan Suresh Padvi,2021300087,COMP,4,Yog Vidya
1,mahesh.patil@spit.ac.in,Mahesh Anil Patil,2021300095,COMP,4,Yog Vidya
2,arshad.mapari@spit.ac.in,Arshad Husenmiya Mapari,2021600043,CSE-AIML,4,Yog Vidya
3,pavan.gole22@spit.ac.in,Pavan Ratan Gole,2022601003,CSE-AIML,4,Yog Vidya
4,rohan.warghade@spit.ac.in,Rohan Janardhan Warghade,2021600071,CSE-AIML,4,Yog Vidya
5,kenneth.rodrigues.22@spit.ac.in,Kenneth David Rodrigues,2022701008,CSE-DS,4,Yog Vidya
6,trupti.g@spit.ac.in,Trupti Gopinath,2018120059,EXTC,8,Yog Vidya
7,abhieram.bandaru@spit.ac.in,Abhieram Bandaru,2021200006,EXTC,4,Yog Vidya
8,vineet.pundpal22@spit.ac.in,Vineet Pundpal,2022201018,EXTC,4,Yog Vidya
9,roshani.patel22@spit.ac.in,Patel Roshani Rajdhar,2022201014,EXTC,4,Yog Vidya
10,rushikesh.mahale22@spit.ac.in,Rishikesh Mahale,2022201012,EXTC,4,Yog Vidya
11,swapnil.chavan@spit.ac.in,Chavan Swapnil Sunil,2020200007,EXTC,6,Yog Vidya
12,jay.nadkarni@spit.ac.in,Jay Nadkarni,2021300081,COMP,4,Yog Vidya
13,sahil.nannaware@spit.ac.in,Sahil Nannaware,2021300083,COMP,4,Yog Vidya
14,aayush.kawathekar@spit.ac.in,Aayush Kawathekar,2019140032,IT,8,Yog Vidya
15,pratiksha.pawar@spit.ac.in,Pratiksha Pawar,2021300099,COMP,4,Read a book
16,amey.wani@spit.ac.in,Amey Wani,2021300138,COMP,4,Read a book
17,rahul.ruke@spit.ac.in,Rahul Rajesh Ruke,2021300105,COMP,4,Read a book
18,vansh.tambi@spit.ac.in,Vansh Tambi,2021300132,COMP,4,Read a book
19,sahil.vedpathak@spit.ac.in,Sahil Vedpathak,2021300135,COMP,4,Read a book

In [47]:
sheet2.sort_values(by=['course', 'sem', 'branch', 'uid'], ascending=True, inplace=True)
sheet2.head(20)

,email,name,uid,branch,sem,course
591,shashank.agrawal@spit.ac.in,Shashank Agrawal,2021510002,MCA,3,Basic Cooking
593,deepanshu.aggarwal@spit.ac.in,Deepanshu Aggarwal,2021300002,COMP,4,Basic Cooking
608,mohammed.ansari@spit.ac.in,Ansari Mohammed Shanouf Valijan,2021300004,COMP,4,Basic Cooking
597,darshana.chothave@spit.ac.in,Darshana Dattatray Chothave,2021300021,COMP,4,Basic Cooking
605,neerja.doshi@spit.ac.in,Neerja J Doshi,2021300029,COMP,4,Basic Cooking
607,apulki.dubey@spit.ac.in,Apulki Dubey,2021300032,COMP,4,Basic Cooking
598,harsh.jain2@spit.ac.in,Harsh Mukesh Jain,2021300048,COMP,4,Basic Cooking
595,priyanka.kadam@spit.ac.in,Priyanka Sunil Kadam,2021300052,COMP,4,Basic Cooking
596,rucha.kulkarni2@spit.ac.in,Rucha Sudhir Kulkarni,2021300067,COMP,4,Basic Cooking
594,sakshi.lonare@spit.ac.in,Sakshi Lonare,2021300069,COMP,4,Basic Cooking
610,vinesh.nadar@spit.ac.in,Vinesh Narayan Nadar,2021300080,COMP,4,Basic Cooking
602,nikita.pawar@spit.ac.in,Nikita Sunil Pawar,2021300098,COMP,4,Basic Cooking
599,omkar.rao@spit.ac.in,Omkar Rao,2021300102,COMP,4,Basic Cooking
601,krutika.shinde@spit.ac.in,Krutika Rupchand Shinde,2021300119,COMP,4,Basic Cooking
600,aditya.shirodkar@spit.ac.in,Aditya Sachin Shirodkar,2021300121,COMP,4,Basic Cooking
592,haridas.singh@spit.ac.in,Haridas Singh,2021300123,COMP,4,Basic Cooking
609,yoshita.singh@spit.ac.in,Yoshita Singh,2021300125,COMP,4,Basic Cooking
606,saad.surve@spit.ac.in,Saad Shaikh Mukhtar Surve,2021300131,COMP,4,Basic Cooking
611,adarsh.tripathi@spit.ac.in,Adarsh Pati Tripathi,2021300133,COMP,4,Basic Cooking
603,yash.waghskar@spit.ac.in,Yash Satish Waghskar,2021300137,COMP,4,Basic Cooking

In [48]:
sheet2.to_csv(os.path.join(data_dir, 'sheet-2.csv'), index=False)

Deleting duplicate rows:

In [49]:
print(f'Number of duplicate rows: {sheet2.duplicated().sum()} / {sheet2.shape[0]}')

Number of duplicate rows: 10 / 1122

In [50]:
sheet2.loc[sheet2.duplicated(), :]

,email,name,uid,branch,sem,course
43,sumit.thakare@spit.ac.in,Sumit Thakare,2020301079,COMP,8,Basics of Fire Safety
577,anish.sambhare22@spit.ac.in,Sambhare Anish Chintamani,2022201019,EXTC,4,Basics of Keyboard playing
105,anushka.acharya@spit.ac.in,Anushka Acharya,2021700001,CSE-DS,4,Integrated Personality Development
104,ronak.thakar@spit.ac.in,Ronak Thakar,2021700066,CSE-DS,4,Integrated Personality Development
117,sakshi.memane22@spit.ac.in,Sakshi Santosh Memane,2022201013,EXTC,4,Integrated Personality Development
116,saniya.pathre22@spit.ac.in,Pathre Saniya Rajesh,2022201016,EXTC,4,Integrated Personality Development
32,dylan.dsouza@spit.ac.in,Dylan Dsouza,2019120020,EXTC,8,Read a book
1095,pratishtha.manjrekar@spit.ac.in,Pratishtha Pradip Manjrekar,2021600041,CSE-AIML,4,Technology Entrepreneurship
1078,rutik.dhere@spit.ac.in,Rutik Bhupal Dhere,201510011,MCA,3,Trekking
170,oum.tipare22@spit.ac.in,Oum Anil Tipare,2022201022,EXTC,4,Working with NGO

In [51]:
sheet2.drop_duplicates(inplace=True, keep='first', ignore_index=True)

In [52]:
sheet2.shape[0]

1112

In [53]:
sheet2.to_csv(os.path.join(data_dir, 'sheet-2.csv'), index=False)

Checking for duplicates based on email:

In [54]:
sheet2.duplicated(subset=['email']).sum()

10

In [55]:
duplicate_emails = set(sheet2['email'][sheet2.duplicated(subset=['email'])].values)
duplicated_rows = sheet2[sheet2['email'].map(lambda x: x in duplicate_emails)].sort_values(by='email')
duplicated_rows

,email,name,uid,branch,sem,course
1111,aayush.kawathekar@spit.ac.in,Aayush Kawathekar,2019140032,IT,8,Yog Vidya
306,aayush.kawathekar@spit.ac.in,Aayush Kawathekar,2019140032,IT,8,Design Thinking
623,janhavi.ghige@spit.ac.in,Janhavi Anil Ghige,2021200034,EXTC,4,Integrated Personality Development
850,janhavi.ghige@spit.ac.in,Janhavi Anil Ghige,2021200034,EXTC,4,Sports
1097,jay.nadkarni@spit.ac.in,Jay Nadkarni,2021300081,COMP,4,Yog Vidya
591,jay.nadkarni@spit.ac.in,Jay Vinayak Nadkarni,2021300081,COMP,4,Integrated Personality Development
868,parth.yogaonkar@spit.ac.in,Parth Sachin Yogaonkar,2020200069,EXTC,6,Sports
428,parth.yogaonkar@spit.ac.in,Parth Yogaonkar,2020200069,EXTC,6,Film Appreciation
1099,rajyavardhan.padvi@spit.ac.in,Rajyavardhan Suresh Padvi,2021300087,COMP,4,Yog Vidya
594,rajyavardhan.padvi@spit.ac.in,Rajyavardhan Suresh Padvi,2021300087,COMP,4,Integrated Personality Development
380,rupali.sawale@spit.ac.in,Rupali Sawale,2021700056,CSE-DS,4,Film Appreciation
588,rupali.sawale@spit.ac.in,Rupali Sawale,2021700056,CSE-DS,3,Integrated Personality Development
1098,sahil.nannaware@spit.ac.in,Sahil Nannaware,2021300083,COMP,4,Yog Vidya
593,sahil.nannaware@spit.ac.in,Sahil Deorao Nannaware,2021300083,COMP,4,Integrated Personality Development
171,shashank.agrawal@spit.ac.in,Shashank Agrawal,2021510002,MCA,3,Design Thinking
0,shashank.agrawal@spit.ac.in,Shashank Agrawal,2021510002,MCA,3,Basic Cooking
58,vinesh.nadar@spit.ac.in,Sanchit Deorao Gajam,2018130011,COMP,8,Basic Cooking
10,vinesh.nadar@spit.ac.in,Vinesh Narayan Nadar,2021300080,COMP,4,Basic Cooking
975,yug.harlalka@spit.ac.in,Yug Prakash Harlalka,2020200022,EXTC,6,Trekking
658,yug.harlalka@spit.ac.in,Yug Prakash Harlalka,2020200022,EXTC,6,Mentorship to Juniors

In [56]:
duplicated_rows.to_csv(os.path.join(data_dir, 'sheet-2-duplicated-rows.csv'), index=False)

Joiining with the courses df:

In [3]:
sheet2 = pd.read_csv(os.path.join(data_dir, 'sheet-2.csv'))
cols_to_keep = list(sheet2.columns) + ['category']
sheet2 = pd.merge(sheet2, courses, left_on='course', right_on='course_name')[cols_to_keep]
sheet2

,email,name,uid,branch,sem,course,category
0,shashank.agrawal@spit.ac.in,Shashank Agrawal,2021510002,MCA,3,Basic Cooking,Intellectual
1,deepanshu.aggarwal@spit.ac.in,Deepanshu Aggarwal,2021300002,COMP,4,Basic Cooking,Intellectual
2,mohammed.ansari@spit.ac.in,Ansari Mohammed Shanouf Valijan,2021300004,COMP,4,Basic Cooking,Intellectual
3,darshana.chothave@spit.ac.in,Darshana Dattatray Chothave,2021300021,COMP,4,Basic Cooking,Intellectual
4,neerja.doshi@spit.ac.in,Neerja J Doshi,2021300029,COMP,4,Basic Cooking,Intellectual
...,...,...,...,...,...,...,...
1107,roshani.patel22@spit.ac.in,Patel Roshani Rajdhar,2022201014,EXTC,4,Yog Vidya,Spiritual
1108,vineet.pundpal22@spit.ac.in,Vineet Pundpal,2022201018,EXTC,4,Yog Vidya,Spiritual
1109,swapnil.chavan@spit.ac.in,Chavan Swapnil Sunil,2020200007,EXTC,6,Yog Vidya,Spiritual
1110,trupti.g@spit.ac.in,Trupti Gopinath,2018120059,EXTC,8,Yog Vidya,Spiritual
1111,aayush.kawathekar@spit.ac.in,Aayush Kawathekar,2019140032,IT,8,Yog Vidya,Spiritual

In [5]:
sheet2.to_csv(os.path.join(data_dir, 'sheet-2.csv'), index=False)