Concatenating all excel sheets in a single CSV file (for even sem 23-24):

In [1]:
import pandas as pd
import os
data_dir = 'data'

Courses:

In [3]:
courses = pd.read_csv(os.path.join(data_dir, 'courses.csv'))
courses

    course_id                            course_name      category
0           1                          Art of living     Spiritual
1           2            Introduction to Bhagvadgita     Spiritual
2           3                              Pranvidya     Spiritual
3           4                              Yog Vidya     Spiritual
4           5  Mentoring School Children (Abhyudaya)        Social
5           6                  Mentorship to Juniors        Social
6           7                                    NSS        Social
7           8          Principle Centered Leadership        Social
8           9                 Teaching Assistantship        Social
9          10                      Terrace Gardening        Social
10         11    Volunteering at Dr. Amte's Anandvan        Social
11         12                          Wall Painting        Social
12         13                       Working with NGO        Social
13         14                                Astitva      Physical
14         15                                 Kathak      Physical
15         16                       Physical Fitness      Physical
16         17                                Running      Physical
17         18                 Self Defense for Women      Physical
18         19                               Skipping      Physical
19         20                                 Sports      Physical
20         21                     Staircase Climbing      Physical
21         22                               Swimming      Physical
22         23                              Taekwondo      Physical
23         24                               Trekking      Physical
24         25                          Basic Cooking  Intellectual
25         26                  Basics of Fire Safety  Intellectual
26         27             Basics of Keyboard playing  Intellectual
27         28            Basics of Music Composition  Intellectual
28         29                        Design Thinking  Intellectual
29         30                      Film Appreciation  Intellectual
30         31            Fundamentals of Photography  Intellectual
31         32                               Idea Lab  Intellectual
32         33                Indian Knowledge System  Intellectual
33         34              Innovation and Creativity  Intellectual
34         35                            Read a book  Intellectual
35         36      Short Film Making/ Cinematography  Intellectual
36         37                      Social Psychology  Intellectual
37         38                          Study of Life  Intellectual
38         39            Technology Entrepreneurship  Intellectual
39         40     Integrated Personality Development     Emotional
40         41       Jeevan Vidya (Work Life Balance)     Emotional
41         42                  Universal Human Value     Emotional

In [4]:
course_names = courses['course_name']

Loading odd sem 23-24.xlsx:

In [7]:
df = pd.read_excel(os.path.join(data_dir, 'odd sem 2023-24.xlsx'), sheet_name=1)

In [8]:
df

,Email Address,Name (as in the college records),UID No.,Class (to be entered in next Semester),Branch,Course Allocated,Sem,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,muzammil.ansari22@spit.ac.in,Mohammed Muzammil Mohd Irfan Ansari,2.022701e+09,TY Sem V,CSE-DS,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mursaleen.batatawala22@spit.ac.in,Batatawala Mursaleen Md Salim,2.022601e+09,TY Sem V,CSE-AIML,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aryan.nathani@spit.ac.in,Aryan Nathani,2.021700e+09,TY Sem V,CSE-DS,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,aditya.jikamade@spit.ac.in,Jikamade Aditya Krishna,2.020300e+09,B. Tech Sem VII,COMP,Universal Human Value (UHV-I),7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,samarth.hirve@spit.ac.in,Samarth Rajendra Hirve,2.021200e+09,TY Sem V,EXTC,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,darshan.jain22@spit.ac.in,Darshan Sanjay Jain,2.022701e+09,TY Sem V,CSE-DS,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,sidhanth.naik22@spit.ac.in,SIDHANTH SANDESH NAIK,2.022200e+09,TY Sem V,EXTC,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ronak.thakar@spit.ac.in,Ronak Satish Thakar,2.021700e+09,TY Sem V,CSE-DS,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,abhieram.bandaru@spit.ac.in,Abhieram Bandaru,2.021200e+09,TY Sem V,EXTC,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,nishant.chamate@spit.ac.in,Nishant Chamate,2.021200e+09,TY Sem V,EXTC,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,varin.mehta22@spit.ac.in,Mehta Varin Amit,2.022300e+09,TY Sem V,COMP,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,pratishtha.manjrekar@spit.ac.in,Pratishtha Pradip Manjrekar,2.021600e+09,TY Sem V,CSE-AIML,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basics of Fire Safety
12,nathan.cardoso@spit.ac.in,Nathan Jude Cardoso,2.021600e+09,TY Sem V,CSE-AIML,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Terrace Gardening (Paras Bag)
13,eshant.chandak@spit.ac.in,Eshant Chandak,2.020300e+09,B. Tech Sem VII,COMP,Innovation and Creativity,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,raya.ghosh22@spit.ac.in,GHOSH RAYA MALAYCHANDAN,2.022200e+09,SY Sem III,EXTC,Universal Human Value (UHV-I),3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,jagdish.aade22@spit.ac.in,jagdish.aade22@spit.ac.in,2.022200e+09,SY Sem III,EXTC,Universal Human Value (UHV-I),3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.
16,abhishek.gupta4@spit.ac.in,ABHISHEK GUPTA,2.021700e+09,TY Sem V,CSE-DS,Universal Human Value (UHV-I),5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,aman.kanojia22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,amey.wani@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,ankit.vishwakarma22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,aryaman.agarwal@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,bhagya.bijlaney@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,chaitanya.chaudhari@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,harsh.walavalkar22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,harshvardhan.pawar@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,laxmi.bodke22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,mahek.parmar22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,nakshatra.shegaonkar22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,nimish.warghat22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,pooja.maurya22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,pranit.lalla@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,prathamesh.paradkar@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,pratiksha.patil22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,raya.ghosh22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,rishabh.srinivasan@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,rohanshu.rathod22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,saad.surve@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,sakshi.pawane@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,samarth.gupta@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,sarvesh.birla@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,varun.adhiya@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,vedika.goliwar22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Will be added in the list after receiving the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,prathamesh.ursal@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,nikhil.singh@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,nimit.sheth22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Will be added in the list after receiving the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,vedant.shah22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,shubham.atrame@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
final = pd.DataFrame(columns=['email', 'name', 'uid', 'branch', 'sem', 'course'])
for sheet_no in range(1, 27): # skipping instructions sheet
    df = pd.read_excel(os.path.join(data_dir, 'odd sem 2023-24.xlsx'), sheet_name=sheet_no)
    try: 
        df.columns = ['email', 'name', 'uid', 'class', 'branch', 'course', 'sem']
        df.drop(columns=['class'], inplace=True)
        df = df[['email', 'name', 'uid', 'branch', 'sem', 'course']]
        final = pd.concat([final, df], ignore_index=True)
    except:
        print(sheet_no)
        print(df.columns)

1
Index(['Email Address', 'Name (as in the college records)', 'UID No.',
       'Class (to be entered in next Semester)', 'Branch', 'Course Allocated',
       'Sem', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14'],
      dtype='object')
5
Index(['Email Address', 'Name (as in the college records)', 'UID No.',
       'Class (to be entered in next Semester)', 'Branch', 'Course Allocated',
       'Sem', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19'],
      dtype='object')
6
Index(['Email Address', 'Name (as in the college records)', 'UID No.',
       'Class (to be entered in next Semester)', 'Branch', 'Course Allocated',
       'Sem', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19'],
      dtype='object')
12
Index(['Email Address', 'Name (as in the college records)', 'UID No.',
       'Class (to be entered in next Semester)', 'Branch', 'Course Allocated',
       'Sem', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15'],
      dtype='object')
19
Index(['Email Address', 'Name (as in the college records)', 'UID No.',
       'Class (to be entered in next Semester)', 'Branch', 'Course Allocated',
       'Sem', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15'],
      dtype='object')
21
Index(['Email Address', 'Name (as in the college records)', 'UID No.',
       'Class (to be entered in next Semester)', 'Branch', 'Course Allocated',
       'Sem', 'Sem.1'],
      dtype='object')
22
Index(['Email Address', 'Name (as in the college records)', 'UID No.',
       'Class (to be entered in next Semester)', 'Branch', 'Course Allocated',
       'Sem', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14'],
      dtype='object')

In [46]:
final.isnull().sum()

email     0
name      0
uid       0
branch    0
sem       0
course    0
dtype: int64

In [47]:
final.head(10)

,email,name,uid,branch,sem,course
0,vijesh.hingu@spit.ac.in,Vijesh Mitesh Hingu,2021300042,COMP,6,ASTITVA
1,dhruvil.doshi@spit.ac.in,Dhruvil Doshi,2021300027,COMP,6,ASTITVA
2,aditya.choudhary@spit.ac.in,Aditya Choudhary,2021300022,COMP,6,ASTITVA
3,kunal.bhatia@spit.ac.in,Kunal Bhatia,2021300010,COMP,6,ASTITVA
4,ameya.dabholkar@spit.ac.in,Ameya Dabholkar,2021300023,COMP,6,ASTITVA
5,siddhant.rao@spit.ac.in,Siddhant Paritosh Rao,2021600055,CSE-AIML,6,ASTITVA
6,rahul.shinde@spit.ac.in,rahul shinde,2021600061,CSE-AIML,6,ASTITVA
7,vansh.talwar@spit.ac.in,Vansh Talwar,2021600064,CSE-AIML,6,ASTITVA
8,divya.raichura@spit.ac.in,Divya Raichura,2021600052,CSE-AIML,6,ASTITVA
9,aditya.kadam@spit.ac.in,Aditya Kadam,2021200046,EXTC,6,ASTITVA

In [48]:
final.shape

(1742, 6)

In [8]:
final.to_csv(os.path.join(data_dir, 'sheet-4.csv'), index=False)

In [49]:
final.sort_values(by=['course', 'sem', 'branch', 'uid'])

,email,name,uid,branch,sem,course
25,soham.ghorpade23@spit.ac.in,Soham Amol Ghorpade,2023300064,COMP,2,ASTITVA
32,aryan.gorde23@spit.ac.in,GORDE ARYAN HITESH,2023300068,COMP,2,ASTITVA
21,omkar.jadhav23@spit.ac.in,Omkar Pandurang Jadhav,2023300082,COMP,2,ASTITVA
24,preetish.kulkarni23@spit.ac.in,Kulkarni Preetish Jayant,2023300125,COMP,2,ASTITVA
23,lalit.mahajan23@spit.ac.in,Mahajan Lalit HIraman,2023300133,COMP,2,ASTITVA
...,...,...,...,...,...,...
1702,akshat.biniwale@spit.ac.in,Akshat Biniwale,2021300014,COMP,6,yoga 1
1701,dewyani.deshmukh@spit.ac.in,dewyani.deshmukh@spit.ac.in,2021300024,COMP,6,yoga 1
1704,ajay.lohar@spit.ac.in,Ajay Sohanlal Lohar,2021200064,EXTC,6,yoga 1
1703,aryan.adav22@spit.ac.in,Aryan Ambarish Adav,2022201001,EXTC,6,yoga 1
1705,nilesh.admane22@spit.ac.in,Nilesh Sahebrao Admane,2022201002,EXTC,6,yoga 1

In [29]:
courses = pd.read_csv(os.path.join(data_dir, 'courses.csv'))
course_names = courses['course_name'].tolist()
course_names

['Art of living',
 'Introduction to Bhagvadgita',
 'Pranvidya',
 'Yog Vidya',
 'Mentoring School Children (Abhyudaya)',
 'Mentorship to Juniors',
 'NSS',
 'Principle Centered Leadership',
 'Teaching Assistantship',
 'Terrace Gardening',
 "Volunteering at Dr. Amte's Anandvan",
 'Wall Painting',
 'Working with NGO',
 'Astitva',
 'Kathak',
 'Physical Fitness',
 'Running',
 'Self Defense for Women',
 'Skipping',
 'Sports',
 'Staircase Climbing',
 'Swimming',
 'Taekwondo',
 'Trekking',
 'Basic Cooking',
 'Basics of Fire Safety',
 'Basics of Keyboard playing',
 'Basics of Music Composition',
 'Design Thinking',
 'Film Appreciation',
 'Fundamentals of Photography',
 'Idea Lab',
 'Indian Knowledge System',
 'Innovation and Creativity',
 'Read a book',
 'Short Film Making/ Cinematography',
 'Social Psychology',
 'Study of Life',
 'Technology Entrepreneurship',
 'Integrated Personality Development',
 'Jeevan Vidya (Work Life Balance)',
 'Universal Human Value']

After cleaning some data in excel, normalizing rest of the courses:

In [33]:
sheet4 = pd.read_csv(os.path.join(data_dir, 'sheet-4.csv'))

In [34]:
sheet4['course'].unique()

array(['Astitva', 'Introduction to Bhagvad Gita',
       'Introduction to Bhagvadgita', 'Introduction to Bhagvatgita',
       'Introduction to Bhagwadgita', 'Introduction To Bhagvadgita',
       'Introduction to Bhagwad Gita', 'Introduction to bhagwadgita',
       'Introduction to Bhagavad GIta', 'Introduction to Bhagavadgita',
       'Introduction of Baghvadgita', 'Bhagwan Gita',
       'Introduction to Bhagvadgita (limit 50 students)', 'Read a book',
       'read a book', 'Basic Cooking', 'Design Thinking',
       'Design thinking', 'Film Appreciation', 'Basics of Fire Safety',
       'Innovation and Creativity', 'Integrated Personality Development',
       'Mentoring School Children (Abhyudaya)',
       'Mentoring School Children (Abhyudaya) ', 'Working with NGO',
       'Fundamentals of Photography', 'Pranvidya', 'pranvidya', 'Running',
       'running', 'Self Defense for Women', 'self Defense for Women',
       'Skipping', 'Skipping ', 'skipiing', 'Sports',
       'Sports-Push ups/Surya Namaskar', 'Sports-Push ups',
       'Sports Push ups', 'Staircase Climbing', 'Staircase Climbing.',
       'Study of Life', 'study of Life', 'Taekwondo',
       "Volunteering at Dr. Amte's Anandvan", 'Wall Painting',
       'Art of living', 'Yog Vidya'], dtype=object)

In [35]:
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

['Introduction to Bhagvad Gita',
 'Introduction to Bhagvatgita',
 'Introduction to Bhagwadgita',
 'Introduction To Bhagvadgita',
 'Introduction to Bhagwad Gita',
 'Introduction to bhagwadgita',
 'Introduction to Bhagavad GIta',
 'Introduction to Bhagavadgita',
 'Introduction of Baghvadgita',
 'Bhagwan Gita',
 'Introduction to Bhagvadgita (limit 50 students)',
 'read a book',
 'Design thinking',
 'Mentoring School Children (Abhyudaya) ',
 'pranvidya',
 'running',
 'self Defense for Women',
 'Skipping ',
 'skipiing',
 'Sports-Push ups/Surya Namaskar',
 'Sports-Push ups',
 'Sports Push ups',
 'Staircase Climbing.',
 'study of Life']

These names have to be the same as that in courses.csv

In [36]:
course_names

['Art of living',
 'Introduction to Bhagvadgita',
 'Pranvidya',
 'Yog Vidya',
 'Mentoring School Children (Abhyudaya)',
 'Mentorship to Juniors',
 'NSS',
 'Principle Centered Leadership',
 'Teaching Assistantship',
 'Terrace Gardening',
 "Volunteering at Dr. Amte's Anandvan",
 'Wall Painting',
 'Working with NGO',
 'Astitva',
 'Kathak',
 'Physical Fitness',
 'Running',
 'Self Defense for Women',
 'Skipping',
 'Sports',
 'Staircase Climbing',
 'Swimming',
 'Taekwondo',
 'Trekking',
 'Basic Cooking',
 'Basics of Fire Safety',
 'Basics of Keyboard playing',
 'Basics of Music Composition',
 'Design Thinking',
 'Film Appreciation',
 'Fundamentals of Photography',
 'Idea Lab',
 'Indian Knowledge System',
 'Innovation and Creativity',
 'Read a book',
 'Short Film Making/ Cinematography',
 'Social Psychology',
 'Study of Life',
 'Technology Entrepreneurship',
 'Integrated Personality Development',
 'Jeevan Vidya (Work Life Balance)',
 'Universal Human Value']

In [37]:
sheet4['course'] = sheet4['course'].map(lambda x: 'Introduction to Bhagvadgita' if x.lower().startswith('introduction') else x)
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

['Bhagwan Gita',
 'read a book',
 'Design thinking',
 'Mentoring School Children (Abhyudaya) ',
 'pranvidya',
 'running',
 'self Defense for Women',
 'Skipping ',
 'skipiing',
 'Sports-Push ups/Surya Namaskar',
 'Sports-Push ups',
 'Sports Push ups',
 'Staircase Climbing.',
 'study of Life']

In [38]:
sheet4['course'] = sheet4['course'].str[0].map(lambda x: x.upper()).values + sheet4['course'].str[1:]
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

['Bhagwan Gita',
 'Design thinking',
 'Mentoring School Children (Abhyudaya) ',
 'Skipping ',
 'Skipiing',
 'Sports-Push ups/Surya Namaskar',
 'Sports-Push ups',
 'Sports Push ups',
 'Staircase Climbing.']

In [39]:
sheet4['course'] = sheet4['course'].str.strip()
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

['Bhagwan Gita',
 'Design thinking',
 'Skipiing',
 'Sports-Push ups/Surya Namaskar',
 'Sports-Push ups',
 'Sports Push ups',
 'Staircase Climbing.']

In [40]:
sheet4['course'] = sheet4['course'].map(lambda x: 'Sports' if x.lower().startswith('sports') else x)
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

['Bhagwan Gita', 'Design thinking', 'Skipiing', 'Staircase Climbing.']

In [41]:
def normalize(course_name):
    if course_name == 'Design thinking':
        return 'Design Thinking'
    if course_name == 'Skipiing':
        return 'Skipping'
    if course_name == 'Staircase Climbing.':
        return 'Staircase Climbing'
    if course_name == 'Bhagwan Gita':
        return 'Introduction to Bhagvadgita'
    return course_name

sheet4['course'] = sheet4['course'].map(normalize)
not_matching = [i for i in sheet4['course'].unique() if i not in course_names]
not_matching

[]

In [42]:
sheet4['name'] = sheet4['name'].str.title()

In [51]:
sheet4.head(20)

,email,name,uid,branch,sem,course
0,vijesh.hingu@spit.ac.in,Vijesh Mitesh Hingu,2021300042,COMP,6,Astitva
1,dhruvil.doshi@spit.ac.in,Dhruvil Doshi,2021300027,COMP,6,Astitva
2,aditya.choudhary@spit.ac.in,Aditya Choudhary,2021300022,COMP,6,Astitva
3,kunal.bhatia@spit.ac.in,Kunal Bhatia,2021300010,COMP,6,Astitva
4,ameya.dabholkar@spit.ac.in,Ameya Dabholkar,2021300023,COMP,6,Astitva
5,siddhant.rao@spit.ac.in,Siddhant Paritosh Rao,2021600055,CSE-AIML,6,Astitva
6,rahul.shinde@spit.ac.in,Rahul Shinde,2021600061,CSE-AIML,6,Astitva
7,vansh.talwar@spit.ac.in,Vansh Talwar,2021600064,CSE-AIML,6,Astitva
8,divya.raichura@spit.ac.in,Divya Raichura,2021600052,CSE-AIML,6,Astitva
9,aditya.kadam@spit.ac.in,Aditya Kadam,2021200046,EXTC,6,Astitva
10,mohammedmaaz.khan22@spit.ac.in,Mohammed Maaz Khan,2022201010,EXTC,6,Astitva
11,lokesh.chaudhari22@spit.ac.in,Lokesh Chauadhari,2022300014,COMP,4,Astitva
12,swayam.sawant22@spit.ac.in,Swayam Sawant,2022300102,COMP,4,Astitva
13,komal.sali23@spit.ac.in,Komal Sali,2023601008,CSE-AIML,4,Astitva
14,shrikant.kabade23@spit.ac.in,Kabade Shrikant Gopinath,2023701002,CSE-DS,4,Astitva
15,shashvat.sangle22@spit.ac.in,Sangle Shashvat Digvijay,2022200103,EXTC,4,Astitva
16,harsh.b.pandey22@spit.ac.in,Pandey Harsh Balkrishna,2022200086,EXTC,4,Astitva
17,vishwas.tripathi22@spit.ac.in,Tripathi Vishwas Santosh,2022200122,EXTC,4,Astitva
18,aditi.rao22@spit.ac.in,Aditi Rao,2022200003,EXTC,4,Astitva
19,adya.jha22@spit.ac.in,Jha Adya,2022200054,EXTC,4,Astitva

In [55]:
sheet4.sort_values(by=['course', 'sem', 'branch', 'uid'], ascending=True, inplace=True)
sheet4.head(20)

,email,name,uid,branch,sem,course
1691,namrata.dalvi23@spit.ac.in,Namrata Dalvi,2023300035,COMP,2,Art of living
1686,ayush.deore23@spit.ac.in,Deore Ayush Nitin,2023300043,COMP,2,Art of living
1687,kimaya.dixit23@spit.ac.in,Kimaya Yatin Dixit,2023300049,COMP,2,Art of living
1692,sneha.jain23@spit.ac.in,Sneha Jain,2023300089,COMP,2,Art of living
1693,grishma.jetani23@spit.ac.in,Jetani Grishma Jayeshbhai,2023300094,COMP,2,Art of living
1688,amruta.johare23@spit.ac.in,Amruta Johare,2023300095,COMP,2,Art of living
1694,srushti.khade23@spit.ac.in,Srushti Sachin Khade,2023300112,COMP,2,Art of living
1685,abhinav.khajurgi23@spit.ac.in,Khajurgi Abhinav Shashidhar,2023300113,COMP,2,Art of living
1695,rasika.kinhikar23@spit.ac.in,Kinhikar Rasika Ajay,2023300119,COMP,2,Art of living
1684,darsh.kothari23@spit.ac.in,Kothari Darsh Amit,2023300123,COMP,2,Art of living
1690,sania.rakhangi23@spit.ac.in,Sania Mohammed Irfan Rakhangi,2023300180,COMP,2,Art of living
1689,heet.shah123@spit.ac.in,Heet Keyur Shah,2023300208,COMP,2,Art of living
1696,onkar.allewar23@Spiit.ac.in,Onkar Allewar,2023800004,CSE,2,Art of living
1697,shivprasad.chougule23@spit.ac.in,Chougule Shivprasad Annasaheb,2023200026,EXTC,2,Art of living
1699,shravani.dhebe23@spit.ac.in,Shravani Dattatray Dhebe,2023200036,EXTC,2,Art of living
1700,kartik.rane23@spit.ac.in,Rane Kartik Santosh,2023200093,EXTC,2,Art of living
1698,atharv.bodake23@spit.ac.in,Atharv Bodake,2023800021,EXTC,2,Art of living
1683,atanu.debnath23@spit.ac.in,Atanu Debnath,2023510014,MCA,2,Art of living
1681,soham.ghaisas22@spit.ac.in,Ghaisas Soham Shailesh,2022200041,EXTC,4,Art of living
1682,aditya.nagane23@spit.ac.in,Aditya Pramod Nagane,2023201001,EXTC,4,Art of living

In [56]:
sheet4.to_csv(os.path.join(data_dir, 'sheet-4.csv'), index=False)