Concatenating all excel sheets in a single CSV file (for even sem 23-24):

In [5]:
import pandas as pd
import os
data_dir = '..\data'

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
C:\Users\arifa\AppData\Local\Temp\ipykernel_20628\3048812472.py:3: SyntaxWarning: invalid escape sequence '\d'
  data_dir = '..\data'

Courses:

In [6]:
courses = pd.read_csv(os.path.join(data_dir, 'courses.csv'))
courses

    course_id                            course_name      category
0           1                          Art of living     Spiritual
1           2            Introduction to Bhagvadgita     Spiritual
2           3                              Pranvidya     Spiritual
3           4                              Yog Vidya     Spiritual
4           5  Mentoring School Children (Abhyudaya)        Social
5           6                  Mentorship to Juniors        Social
6           7                                    NSS        Social
7           8          Principle Centered Leadership        Social
8           9                 Teaching Assistantship        Social
9          10                      Terrace Gardening        Social
10         11    Volunteering at Dr. Amte's Anandvan        Social
11         12                          Wall Painting        Social
12         13                       Working with NGO        Social
13         14                                Astitva      Physical
14         15                                 Kathak      Physical
15         16                       Physical Fitness      Physical
16         17                                Running      Physical
17         18                 Self Defense for Women      Physical
18         19                               Skipping      Physical
19         20                                 Sports      Physical
20         21                     Staircase Climbing      Physical
21         22                               Swimming      Physical
22         23                              Taekwondo      Physical
23         24                               Trekking      Physical
24         25                          Basic Cooking  Intellectual
25         26                  Basics of Fire Safety  Intellectual
26         27             Basics of Keyboard playing  Intellectual
27         28            Basics of Music Composition  Intellectual
28         29                        Design Thinking  Intellectual
29         30                      Film Appreciation  Intellectual
30         31            Fundamentals of Photography  Intellectual
31         32                               Idea Lab  Intellectual
32         33                Indian Knowledge System  Intellectual
33         34              Innovation and Creativity  Intellectual
34         35                            Read a book  Intellectual
35         36      Short Film Making/ Cinematography  Intellectual
36         37                      Social Psychology  Intellectual
37         38                          Study of Life  Intellectual
38         39            Technology Entrepreneurship  Intellectual
39         40     Integrated Personality Development     Emotional
40         41       Jeevan Vidya (Work Life Balance)     Emotional
41         42                  Universal Human Value     Emotional

In [7]:
course_names = courses['course_name']

Loading odd sem 23-24.xlsx:

In [8]:
df = pd.read_excel(os.path.join(data_dir, 'odd sem 2023-24.xlsx'), sheet_name=1)

In [20]:
df.head(10)

,email,name,uid,branch,sem,course
0,navinder.singh@spit.ac.in,Navinder Singh,2020200058,EXTC,7,Basic Cooking
1,madhura.chitale@spit.ac.in,Chitale Madhura Ramkrishna,2020300005,COMP,7,Basic Cooking
2,aakanksha.dhawale@spit.ac.in,Aakanksha Dhawale,2020300008,COMP,7,Basic Cooking
3,srushti.haryan@spit.ac.in,Haryan Srushti Manvendra,2020300018,COMP,7,Basic Cooking
4,manushree.dubey@spit.ac.in,Manushree Dubey,2020300010,COMP,7,Basic Cooking
5,kunal.thakur@spit.ac.in,Kunal Thakur,2020200060,EXTC,7,Basic Cooking
6,prathamesh.redij@spit.ac.in,Prathamesh Sanjay Redij,2020300058,COMP,7,Basic cooking
7,krish.shah@spit.ac.in,Krish Shah,2020300061,COMP,7,Basic cooking
8,shivalik.pandita@spit.ac.in,Shivalik Pandita,2020300049,COMP,7,Basic cooking
9,arnav.joglekar22@spit.ac.in,Arnav Ajay Joglekar,2022600002,CSE-AIML,3,Basic cooking

In [10]:
final = pd.DataFrame(columns=['email', 'name', 'uid', 'branch', 'sem', 'course'])
for sheet_no in range(1, 27): # skipping instructions sheet
    df = pd.read_excel(os.path.join(data_dir, 'odd sem 2023-24.xlsx'), sheet_name=sheet_no)
    df.columns = ['email', 'name', 'uid', 'class', 'branch', 'course', 'sem']
    df.drop(columns=['class'], inplace=True)
    df = df[['email', 'name', 'uid', 'branch', 'sem', 'course']]
    final = pd.concat([final, df], ignore_index=True)

C:\Users\arifa\AppData\Local\Temp\ipykernel_20628\1154443729.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final = pd.concat([final, df], ignore_index=True)

In [11]:
final.isnull().sum()

email      4
name      36
uid       38
branch    37
sem       37
course    11
dtype: int64

In [12]:
final.shape

(1430, 6)

In [13]:
na_rows = list(set(final.index) - set(final.dropna().index))
final.loc[na_rows, :]

,email,name,uid,branch,sem,course
516,krutuja.bundele@spit.ac.in,Krutuja Bundele,2.021200e+09,EXTC,5.0,NaN
133,mihir.shirsath22@spit.ac.in,Mihir Ram Shirsath,2.022510e+09,MCA,3.0,NaN
134,shubham.golwal@spit.ac.in,Shubham Golwal,2.020300e+09,COMP,7.0,NaN
158,jagdish.aade22@spit.ac.in,NaN,NaN,NaN,NaN,Study of life of (Dr.Ambedkar / Mahatma Gandhi...
17,aman.kanojia22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
18,amey.wani@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
19,ankit.vishwakarma22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
20,aryaman.agarwal@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
21,bhagya.bijlaney@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
22,chaitanya.chaudhari@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
23,harsh.walavalkar22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
24,harshvardhan.pawar@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
25,laxmi.bodke22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
26,mahek.parmar22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
27,nakshatra.shegaonkar22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
28,nimish.warghat22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
29,pooja.maurya22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
30,pranit.lalla@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
31,prathamesh.paradkar@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
32,pratiksha.patil22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
33,raya.ghosh22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
34,rishabh.srinivasan@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
35,rohanshu.rathod22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
36,saad.surve@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
37,sakshi.pawane@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
38,samarth.gupta@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
39,sarvesh.birla@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
40,varun.adhiya@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
41,vedika.goliwar22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
42,Will be added in the list after receiving the ...,NaN,NaN,NaN,NaN,NaN
43,prathamesh.ursal@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
44,nikhil.singh@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
45,nimit.sheth22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
46,Will be added in the list after receiving the ...,NaN,NaN,NaN,NaN,NaN
47,vedant.shah22@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
48,shubham.atrame@spit.ac.in,NaN,NaN,NaN,NaN,Universal Human Value (UHV-I)
162,NaN,NaN,NaN,NaN,NaN,NaN
1329,nikhil.saraf@spit.ac.in,Nikhil Vijay Saraf,2.020100e+09,ETRX,7.0,NaN
163,NaN,NaN,NaN,NaN,NaN,NaN
164,NaN,NaN,NaN,NaN,NaN,NaN
165,NaN,Follwing Students(earlier Not graded /not comp...,NaN,NaN,NaN,NaN
1242,harsh.dugar22@spit.ac.in,DUGAR HARSH ASHOK,NaN,EXTC,3.0,Fundamentals of Photography.
113,abhijit.khune@spit.ac.in,ABHIJIT MARUTI KHUNE,2.020100e+09,ETRX,7.0,NaN

Dropping missing values:

In [14]:
final.loc[na_rows, :].shape[0]

43

In [15]:
final.dropna(inplace=True)
final.isnull().sum()

email     0
name      0
uid       0
branch    0
sem       0
course    0
dtype: int64

In [16]:
final.head(10)

,email,name,uid,branch,sem,course
0,muzammil.ansari22@spit.ac.in,Mohammed Muzammil Mohd Irfan Ansari,2.022701e+09,CSE-DS,5.0,Universal Human Value (UHV-I)
1,mursaleen.batatawala22@spit.ac.in,Batatawala Mursaleen Md Salim,2.022601e+09,CSE-AIML,5.0,Universal Human Value (UHV-I)
2,aryan.nathani@spit.ac.in,Aryan Nathani,2.021700e+09,CSE-DS,5.0,Universal Human Value (UHV-I)
3,aditya.jikamade@spit.ac.in,Jikamade Aditya Krishna,2.020300e+09,COMP,7.0,Universal Human Value (UHV-I)
4,samarth.hirve@spit.ac.in,Samarth Rajendra Hirve,2.021200e+09,EXTC,5.0,Universal Human Value (UHV-I)
5,darshan.jain22@spit.ac.in,Darshan Sanjay Jain,2.022701e+09,CSE-DS,5.0,Universal Human Value (UHV-I)
6,sidhanth.naik22@spit.ac.in,SIDHANTH SANDESH NAIK,2.022200e+09,EXTC,5.0,Universal Human Value (UHV-I)
7,ronak.thakar@spit.ac.in,Ronak Satish Thakar,2.021700e+09,CSE-DS,5.0,Universal Human Value (UHV-I)
8,abhieram.bandaru@spit.ac.in,Abhieram Bandaru,2.021200e+09,EXTC,5.0,Universal Human Value (UHV-I)
9,nishant.chamate@spit.ac.in,Nishant Chamate,2.021200e+09,EXTC,5.0,Universal Human Value (UHV-I)

In [17]:
final.shape

(1387, 6)

In [23]:
final.to_csv(os.path.join(data_dir, 'sheet-3.csv'), index=False)

In [24]:
courses = pd.read_csv(os.path.join(data_dir, 'courses.csv'))
course_names = courses['course_name'].tolist()
course_names

['Art of living',
 'Introduction to Bhagvadgita',
 'Pranvidya',
 'Yog Vidya',
 'Mentoring School Children (Abhyudaya)',
 'Mentorship to Juniors',
 'NSS',
 'Principle Centered Leadership',
 'Teaching Assistantship',
 'Terrace Gardening',
 "Volunteering at Dr. Amte's Anandvan",
 'Wall Painting',
 'Working with NGO',
 'Astitva',
 'Kathak',
 'Physical Fitness',
 'Running',
 'Self Defense for Women',
 'Skipping',
 'Sports',
 'Staircase Climbing',
 'Swimming',
 'Taekwondo',
 'Trekking',
 'Basic Cooking',
 'Basics of Fire Safety',
 'Basics of Keyboard playing',
 'Basics of Music Composition',
 'Design Thinking',
 'Film Appreciation',
 'Fundamentals of Photography',
 'Idea Lab',
 'Indian Knowledge System',
 'Innovation and Creativity',
 'Read a book',
 'Short Film Making/ Cinematography',
 'Social Psychology',
 'Study of Life',
 'Technology Entrepreneurship',
 'Integrated Personality Development',
 'Jeevan Vidya (Work Life Balance)',
 'Universal Human Value']

After cleaning some data in excel, normalizing rest of the courses:

In [26]:
sheet3 = pd.read_csv(os.path.join(data_dir, 'sheet-3.csv'))
sheet3['course'].unique()

array(['Universal Human Value', 'Innovation and Creativity', 'Trekking',
       'Trekking (fees Rs. 1000 as partial contribution)',
       'Trekking ( fees Rs.1000)', 'Trek', 'trek', 'College Trekking',
       'Trekking (fees Rs. 1000 as a partial contribution)',
       'Trekking( fees rs 1000 as a partial contribution)',
       'Study of life of (Dr.Ambedkar / Mahatma Gandhi / Mahatma Phule/Gadge Maharaj/Rashtrasant Tukdoji Maharaj/Sardar Patel )',
       'Study of life of dr. Br ambedkar', 'Study of life of DR.Ambedkar',
       'Introduction to Bhagvadgita', 'Introduction to bhagvadgita',
       'introduction to bhagvadgita', 'Introduction to Bhagwad Geeta',
       'Introduction to Bhagvad Gita', 'Design Thinking',
       'Design Thinking (online)', 'Design Thinking(Online)',
       'Innovation and Creativity (Online)', 'Innovative and Creativity',
       'Working with NGO', 'Wall Painting', 'Wall Painting ',
       'Terrace Gardening', 'Staircase Climbing', 'Skipping',
       'Self Defense for Women', 'Running', 'Running ', 'running ',
       'Runnning', 'Read a book', 'Pranvidya (Online limit 25 students)',
       'Pranvidya', 'NSS', 'Mentoring School Children (Abhyudaya)',
       'Integrated Personality Development', 'Sports',
       'Sports(volleyball)', 'Sports (Sports)', 'Sports(Sports)',
       'Sports ( Sports/ vollyball/ kabbadi )',
       'Sports(Sports/Volleyball/Kabaddi)', 'SPORTS (Sports)',
       'Sports(kabbadi)', 'Sports ( Sports )', 'Sports(Sports/Kabaddi)',
       'Sports kabaddi', 'Sports Volleyball', 'Sports-Volleyball',
       'Sports-volleyball', 'Sports - Sports',
       'Sports( Sports/volleyball/kabaddi)', 'SPORTS(Sports)',
       'Sports(kabaddi)', 'Sports(Volleyball)', 'Sports(Kabaddi)',
       'Sports (Sports,volleyball)', 'Sports (Kabaddi)',
       'Sports( Sports/ volleyball)', 'Sports(Sports/volleyball)',
       'Indian Knowledge System', 'Idea Lab',
       'Fundamentals of Photography', 'Fundamentals of Photography.',
       'Fundamentals of Photography ', 'Film Appreciation',
       'Flim appreciation', 'Basic of Fire Safety',
       'Basics of Fire Safety', 'Basic Cooking'], dtype=object)

In [28]:
not_matching = [i for i in sheet3['course'].unique() if i not in course_names]
not_matching

['Trekking (fees Rs. 1000 as partial contribution)',
 'Trekking ( fees Rs.1000)',
 'Trek',
 'trek',
 'College Trekking',
 'Trekking (fees Rs. 1000 as a partial contribution)',
 'Trekking( fees rs 1000 as a partial contribution)',
 'Study of life of (Dr.Ambedkar / Mahatma Gandhi / Mahatma Phule/Gadge Maharaj/Rashtrasant Tukdoji Maharaj/Sardar Patel )',
 'Study of life of dr. Br ambedkar',
 'Study of life of DR.Ambedkar',
 'Introduction to bhagvadgita',
 'introduction to bhagvadgita',
 'Introduction to Bhagwad Geeta',
 'Introduction to Bhagvad Gita',
 'Design Thinking (online)',
 'Design Thinking(Online)',
 'Innovation and Creativity (Online)',
 'Innovative and Creativity',
 'Wall Painting ',
 'Running ',
 'running ',
 'Runnning',
 'Pranvidya (Online limit 25 students)',
 'Sports(volleyball)',
 'Sports (Sports)',
 'Sports(Sports)',
 'Sports ( Sports/ vollyball/ kabbadi )',
 'Sports(Sports/Volleyball/Kabaddi)',
 'SPORTS (Sports)',
 'Sports(kabbadi)',
 'Sports ( Sports )',
 'Sports(Sports/Kabaddi)',
 'Sports kabaddi',
 'Sports Volleyball',
 'Sports-Volleyball',
 'Sports-volleyball',
 'Sports - Sports',
 'Sports( Sports/volleyball/kabaddi)',
 'SPORTS(Sports)',
 'Sports(kabaddi)',
 'Sports(Volleyball)',
 'Sports(Kabaddi)',
 'Sports (Sports,volleyball)',
 'Sports (Kabaddi)',
 'Sports( Sports/ volleyball)',
 'Sports(Sports/volleyball)',
 'Fundamentals of Photography.',
 'Fundamentals of Photography ',
 'Flim appreciation',
 'Basic of Fire Safety']

These names have to be the same as that in courses.csv

In [29]:
course_names

['Art of living',
 'Introduction to Bhagvadgita',
 'Pranvidya',
 'Yog Vidya',
 'Mentoring School Children (Abhyudaya)',
 'Mentorship to Juniors',
 'NSS',
 'Principle Centered Leadership',
 'Teaching Assistantship',
 'Terrace Gardening',
 "Volunteering at Dr. Amte's Anandvan",
 'Wall Painting',
 'Working with NGO',
 'Astitva',
 'Kathak',
 'Physical Fitness',
 'Running',
 'Self Defense for Women',
 'Skipping',
 'Sports',
 'Staircase Climbing',
 'Swimming',
 'Taekwondo',
 'Trekking',
 'Basic Cooking',
 'Basics of Fire Safety',
 'Basics of Keyboard playing',
 'Basics of Music Composition',
 'Design Thinking',
 'Film Appreciation',
 'Fundamentals of Photography',
 'Idea Lab',
 'Indian Knowledge System',
 'Innovation and Creativity',
 'Read a book',
 'Short Film Making/ Cinematography',
 'Social Psychology',
 'Study of Life',
 'Technology Entrepreneurship',
 'Integrated Personality Development',
 'Jeevan Vidya (Work Life Balance)',
 'Universal Human Value']

Correcting trekking related spelling mistakes:

In [30]:
sheet3['course'] = sheet3['course'].map(lambda x: 'Trekking' if 'trek' in x.lower() else x)
not_matching = [i for i in sheet3['course'].unique() if i not in course_names]
not_matching

['Study of life of (Dr.Ambedkar / Mahatma Gandhi / Mahatma Phule/Gadge Maharaj/Rashtrasant Tukdoji Maharaj/Sardar Patel )',
 'Study of life of dr. Br ambedkar',
 'Study of life of DR.Ambedkar',
 'Introduction to bhagvadgita',
 'introduction to bhagvadgita',
 'Introduction to Bhagwad Geeta',
 'Introduction to Bhagvad Gita',
 'Design Thinking (online)',
 'Design Thinking(Online)',
 'Innovation and Creativity (Online)',
 'Innovative and Creativity',
 'Wall Painting ',
 'Running ',
 'running ',
 'Runnning',
 'Pranvidya (Online limit 25 students)',
 'Sports(volleyball)',
 'Sports (Sports)',
 'Sports(Sports)',
 'Sports ( Sports/ vollyball/ kabbadi )',
 'Sports(Sports/Volleyball/Kabaddi)',
 'SPORTS (Sports)',
 'Sports(kabbadi)',
 'Sports ( Sports )',
 'Sports(Sports/Kabaddi)',
 'Sports kabaddi',
 'Sports Volleyball',
 'Sports-Volleyball',
 'Sports-volleyball',
 'Sports - Sports',
 'Sports( Sports/volleyball/kabaddi)',
 'SPORTS(Sports)',
 'Sports(kabaddi)',
 'Sports(Volleyball)',
 'Sports(Kabaddi)',
 'Sports (Sports,volleyball)',
 'Sports (Kabaddi)',
 'Sports( Sports/ volleyball)',
 'Sports(Sports/volleyball)',
 'Fundamentals of Photography.',
 'Fundamentals of Photography ',
 'Flim appreciation',
 'Basic of Fire Safety']

Changing all study of life courses to 'Study of Life':

In [31]:
sheet3['course'] = sheet3['course'].map(lambda x: 'Study of Life' if 'study of life' in x.lower() else x)
not_matching = [i for i in sheet3['course'].unique() if i not in course_names]
not_matching

['Introduction to bhagvadgita',
 'introduction to bhagvadgita',
 'Introduction to Bhagwad Geeta',
 'Introduction to Bhagvad Gita',
 'Design Thinking (online)',
 'Design Thinking(Online)',
 'Innovation and Creativity (Online)',
 'Innovative and Creativity',
 'Wall Painting ',
 'Running ',
 'running ',
 'Runnning',
 'Pranvidya (Online limit 25 students)',
 'Sports(volleyball)',
 'Sports (Sports)',
 'Sports(Sports)',
 'Sports ( Sports/ vollyball/ kabbadi )',
 'Sports(Sports/Volleyball/Kabaddi)',
 'SPORTS (Sports)',
 'Sports(kabbadi)',
 'Sports ( Sports )',
 'Sports(Sports/Kabaddi)',
 'Sports kabaddi',
 'Sports Volleyball',
 'Sports-Volleyball',
 'Sports-volleyball',
 'Sports - Sports',
 'Sports( Sports/volleyball/kabaddi)',
 'SPORTS(Sports)',
 'Sports(kabaddi)',
 'Sports(Volleyball)',
 'Sports(Kabaddi)',
 'Sports (Sports,volleyball)',
 'Sports (Kabaddi)',
 'Sports( Sports/ volleyball)',
 'Sports(Sports/volleyball)',
 'Fundamentals of Photography.',
 'Fundamentals of Photography ',
 'Flim appreciation',
 'Basic of Fire Safety']

Trimming all leading and trailing spaces:

In [32]:
sheet3['course'] = sheet3['course'].str.strip()
not_matching = [i for i in sheet3['course'].unique() if i not in course_names]
not_matching

['Introduction to bhagvadgita',
 'introduction to bhagvadgita',
 'Introduction to Bhagwad Geeta',
 'Introduction to Bhagvad Gita',
 'Design Thinking (online)',
 'Design Thinking(Online)',
 'Innovation and Creativity (Online)',
 'Innovative and Creativity',
 'running',
 'Runnning',
 'Pranvidya (Online limit 25 students)',
 'Sports(volleyball)',
 'Sports (Sports)',
 'Sports(Sports)',
 'Sports ( Sports/ vollyball/ kabbadi )',
 'Sports(Sports/Volleyball/Kabaddi)',
 'SPORTS (Sports)',
 'Sports(kabbadi)',
 'Sports ( Sports )',
 'Sports(Sports/Kabaddi)',
 'Sports kabaddi',
 'Sports Volleyball',
 'Sports-Volleyball',
 'Sports-volleyball',
 'Sports - Sports',
 'Sports( Sports/volleyball/kabaddi)',
 'SPORTS(Sports)',
 'Sports(kabaddi)',
 'Sports(Volleyball)',
 'Sports(Kabaddi)',
 'Sports (Sports,volleyball)',
 'Sports (Kabaddi)',
 'Sports( Sports/ volleyball)',
 'Sports(Sports/volleyball)',
 'Fundamentals of Photography.',
 'Flim appreciation',
 'Basic of Fire Safety']

Normalizing all sports related courses:

In [33]:
sheet3['course'] = sheet3['course'].map(lambda x: 'Sports' if 'sports' in x.lower() else x)
not_matching = [i for i in sheet3['course'].unique() if i not in course_names]
not_matching

['Introduction to bhagvadgita',
 'introduction to bhagvadgita',
 'Introduction to Bhagwad Geeta',
 'Introduction to Bhagvad Gita',
 'Design Thinking (online)',
 'Design Thinking(Online)',
 'Innovation and Creativity (Online)',
 'Innovative and Creativity',
 'running',
 'Runnning',
 'Pranvidya (Online limit 25 students)',
 'Fundamentals of Photography.',
 'Flim appreciation',
 'Basic of Fire Safety']

Correcting 'Intro to bhagvadgita':

In [34]:
sheet3['course'] = sheet3['course'].map(lambda x: 'Introduction to Bhagvadgita' if x.lower().startswith('intro') else x)
not_matching = [i for i in sheet3['course'].unique() if i not in course_names]
not_matching

['Design Thinking (online)',
 'Design Thinking(Online)',
 'Innovation and Creativity (Online)',
 'Innovative and Creativity',
 'running',
 'Runnning',
 'Pranvidya (Online limit 25 students)',
 'Fundamentals of Photography.',
 'Flim appreciation',
 'Basic of Fire Safety']

Removing 'online':

In [35]:
sheet3['course'] = sheet3['course'].map(lambda x: 'Introduction to Bhagvadgita' if '(online' in x.lower() else x)
not_matching = [i for i in sheet3['course'].unique() if i not in course_names]
not_matching

['Innovative and Creativity',
 'running',
 'Runnning',
 'Fundamentals of Photography.',
 'Flim appreciation',
 'Basic of Fire Safety']

Running:

In [37]:
sheet3['course'] = sheet3['course'].map(lambda x: 'Running' if x.lower().startswith('run') else x)
not_matching = [i for i in sheet3['course'].unique() if i not in course_names]
not_matching

['Innovative and Creativity',
 'Fundamentals of Photography.',
 'Flim appreciation',
 'Basic of Fire Safety']

In [38]:
def normalize(course_name):
    if course_name == 'Innovative and Creativity':
        return 'Innovation and Creativity'
    if course_name == 'Basic of Fire Safety':
        return 'Basics of Fire Safety'
    if course_name == 'Flim appreciation':
        return 'Film Appreciation'
    if course_name == 'Fundamentals of Photography.':
        return 'Fundamentals of Photography'
    return course_name

sheet3['course'] = sheet3['course'].map(normalize)
not_matching = [i for i in sheet3['course'].unique() if i not in course_names]
not_matching

[]

Converting all names to title case:

In [39]:
sheet3['name'] = sheet3['name'].str.title()

In [40]:
sheet3.head(20)

,email,name,uid,branch,sem,course
0,muzammil.ansari22@spit.ac.in,Mohammed Muzammil Mohd Irfan Ansari,2022701001,CSE-DS,5,Universal Human Value
1,mursaleen.batatawala22@spit.ac.in,Batatawala Mursaleen Md Salim,2022601001,CSE-AIML,5,Universal Human Value
2,aryan.nathani@spit.ac.in,Aryan Nathani,2021700041,CSE-DS,5,Universal Human Value
3,aditya.jikamade@spit.ac.in,Jikamade Aditya Krishna,2020300024,COMP,7,Universal Human Value
4,samarth.hirve@spit.ac.in,Samarth Rajendra Hirve,2021200037,EXTC,5,Universal Human Value
5,darshan.jain22@spit.ac.in,Darshan Sanjay Jain,2022701005,CSE-DS,5,Universal Human Value
6,sidhanth.naik22@spit.ac.in,Sidhanth Sandesh Naik,2022200108,EXTC,5,Universal Human Value
7,ronak.thakar@spit.ac.in,Ronak Satish Thakar,2021700066,CSE-DS,5,Universal Human Value
8,abhieram.bandaru@spit.ac.in,Abhieram Bandaru,2021200006,EXTC,5,Universal Human Value
9,nishant.chamate@spit.ac.in,Nishant Chamate,2021200018,EXTC,5,Universal Human Value
10,varin.mehta22@spit.ac.in,Mehta Varin Amit,2022300058,COMP,5,Universal Human Value
11,pratishtha.manjrekar@spit.ac.in,Pratishtha Pradip Manjrekar,2021600041,CSE-AIML,5,Universal Human Value
12,nathan.cardoso@spit.ac.in,Nathan Jude Cardoso,2021600009,CSE-AIML,5,Universal Human Value
13,eshant.chandak@spit.ac.in,Eshant Chandak,2020300003,COMP,7,Innovation and Creativity
14,raya.ghosh22@spit.ac.in,Ghosh Raya Malaychandan,2022200042,EXTC,3,Universal Human Value
15,jagdish.aade22@spit.ac.in,Jagdish.Aade22@Spit.Ac.In,2022200001,EXTC,3,Universal Human Value
16,abhishek.gupta4@spit.ac.in,Abhishek Gupta,2021700027,CSE-DS,5,Universal Human Value
17,suyog.shah@spit.ac.in,Suyig Sachin Shah,2020300064,COMP,7,Trekking
18,noman.khan@spit.ac.in,Khan Noman Asrar Ahmed,2020300027,COMP,7,Trekking
19,tanmay.gadgil@spit.ac.in,Tanmay Manish Gadgil,2020200012,EXTC,7,Trekking

In [41]:
sheet3.sort_values(by=['course', 'sem', 'branch', 'uid'], ascending=True, inplace=True)
sheet3.head(20)

,email,name,uid,branch,sem,course
1372,manan.kher22@spit.ac.in,Kher Manan Sonali,2022300049,COMP,3,Basic Cooking
1373,sneha.sambare22@spit.ac.in,Sambare Sneha Sanjay,2022300092,COMP,3,Basic Cooking
1365,arnav.joglekar22@spit.ac.in,Arnav Ajay Joglekar,2022600002,CSE-AIML,3,Basic Cooking
1371,parnika.das22@spit.ac.in,Parnika Das,2022600038,CSE-AIML,3,Basic Cooking
1375,ruchi.bhanushali22@spit.ac.in,Bhanushali Ruchi Kanji,2022700005,CSE-DS,3,Basic Cooking
1374,harsh.chhallani22@spit.ac.in,Chhallani Harsh Santosh,2022200020,EXTC,3,Basic Cooking
1370,tanvi.shinde22@spit.ac.in,Tanvi Poornachandra Shinde,2022200119,EXTC,3,Basic Cooking
1376,rashi.khandelwal@spit.ac.in,Rashi Khandelwal,2021510028,MCA,3,Basic Cooking
1383,om.doshi@spit.ac.in,Om Doshi,2021300030,COMP,5,Basic Cooking
1378,abhimanyu.kapoor@spit.ac.in,Abhimanyu Kapoor,2021300055,COMP,5,Basic Cooking
1377,m.reddy@spit.ac.in,M Sheshasai Kumar Reddy,2021300104,COMP,5,Basic Cooking
1381,sahil.vedpathak@spit.ac.in,Sahil Vedpathak,2021300135,COMP,5,Basic Cooking
1385,sajid.aga@spit.ac.in,Sajid Mohammad Aga,2021600002,CSE-AIML,5,Basic Cooking
1384,darshit.bhagtani@spit.ac.in,Darshit Bhagtani,2021700006,CSE-DS,5,Basic Cooking
1379,sarthak.jaiswal@spit.ac.in,Sarthak Jaiswal,2021200041,EXTC,5,Basic Cooking
1380,siddhi.mardhekar@spit.ac.in,Siddhi Dinkar Mardhekar,2021200068,EXTC,5,Basic Cooking
1382,sayee.pendkar@spit.ac.in,Sayee,2021200092,EXTC,5,Basic Cooking
1357,madhura.chitale@spit.ac.in,Chitale Madhura Ramkrishna,2020300005,COMP,7,Basic Cooking
1358,aakanksha.dhawale@spit.ac.in,Aakanksha Dhawale,2020300008,COMP,7,Basic Cooking
1360,manushree.dubey@spit.ac.in,Manushree Dubey,2020300010,COMP,7,Basic Cooking

In [43]:
sheet3.to_csv(os.path.join(data_dir, 'sheet-3.csv'), index=False)